### ISSUE TITLE
Mirror pods never show as ready

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#10433]
I dropped some configs on a machine, and then saw it in the API (yay).  But they show as not-ready.

```
NAME                                           READY     REASON    RESTARTS   AGE
dns-proxy-kubernetes-minion-hiko               0/2       Pending   0          1s
fluentd-cloud-logging-kubernetes-minion-0j4m   1/1       Running   0          23h
fluentd-cloud-logging-kubernetes-minion-gttp   1/1       Running   0          23h
fluentd-cloud-logging-kubernetes-minion-hiko   1/1       Running   0          23h
fluentd-cloud-logging-kubernetes-minion-vv0d   1/1       Running   0          23h
hostnames-04rup                                1/1       Running   0          22m
hostnames-14qb3                                1/1       Running   0          22m
hostnames-320gg                                1/1       Running   0          22m
hostnames-p9jwo                                1/1       Running   0          22m
hostnames-proxy-kubernetes-minion-hiko         0/1       Pending   0          0s
hostnames-rtva6                                1/1       Running   0          22m
kube-dns-v4-cf036                              3/3       Running   0          23h
monitoring-heapster-v4-dthvf                   1/1       Running   1          23h
monitoring-influx-grafana-v1-ozxel             2/2       Running   0          23h
```

The dns-proxy and hostnames-proxy have been running for 20  minutes or more, as per `docker ps`

P1 for initial assessment.

**Comment by dchen1107** [comment]
I noticed that fluentd-cloud-logging-kubernetes-minion-XXXX other mirror pods are running properly: 

```
fluentd-cloud-logging-kubernetes-minion-0j4m   1/1       Running   0          23h
fluentd-cloud-logging-kubernetes-minion-gttp   1/1       Running   0          23h
fluentd-cloud-logging-kubernetes-minion-hiko   1/1       Running   0          23h
fluentd-cloud-logging-kubernetes-minion-vv0d   1/1       Running   0          23h
```

Could you please run kubectl describe pods hostnames-proxy-kubernetes-minion-hiko? Sounds like that the containers in that pod never run.

**Comment by thockin** [comment]
Actually, it looks like the mirror pod is appearing and disappearing.  Dawn saw it.  Maybe this is the same as #10434 

my manifest file

```
apiVersion: v1
kind: Pod
metadata:
  name: hostnames-proxy
spec:
  containers:
  - name: proxy-tcp
    image: gcr.io/google_containers/proxy-to-service:v1
    args: [ "tcp", "80", "hostnames.default" ]
    ports:
    - name: tcp
      protocol: TCP
      containerPort: 80
      hostPort: 80
```
