### ISSUE TITLE
Possible data corruption on rbd storage

### ISSUE THREAD

**Issue by farcaller** [GoogleCloudPlatform/kubernetes#10462]
etcd cluster backing apiserver died spontaneously, after restart apiserver pulled up the pods on different machines. Node storage was backed by ext4 over rbd, which became mounted on several nodes at once. That could have possibly led to data corruption.

I guess that the proper way to mount rbd volume is to take a lock on it first, which will at least fail if it's locked somewhere else, requiring manual intervention, but not destroying data. The lock should be optional, in case a proper cluster fs is mounted over the rbd.

In this case there was clearly no need for accessing the data from several pods so ext4 is deemed a proper fs.

**Comment by thockin** [comment]
@rootfs

**Comment by rootfs** [comment]
@farcaller want to get some detail. How is your pod-to-rbd mapping like? Since rbd image is a block device, it can be used by one pod at a time. 

I am not sure if locking is a proper way to go -  if the pod holds a lock but dies in the middle of mounting, the rbd image (or any other volume type) is then excluded from access. In such case, a high level coordination at apiserver is a better place to resolve this problem.

**Comment by farcaller** [comment]
Here's my rc:

```yaml
apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: prometheus
  labels:
    name: prometheus
spec:
  replicas: 1
  selector:
    name: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        name: prometheus
    spec:
      containers:
        - name: prometheus
          image: docker-registry.default.svc.kube.local/prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-data
              mountPath: /prometheus
      volumes:
        - name: prometheus-data
          rbd:
            monitors:
              - 10.200.0.1:6789
              - 10.201.0.1:6789
              - 10.202.0.1:6789
            pool: kube-common
            image: prometheus-data
            fsType: ext4
            user: admin
            keyring: /etc/ceph/ceph.client.admin.keyring
```

I guess it's better to have a lock to be cleaned up manually rather than to have non-cluster fs to be mounted in several locations at once?
