### ISSUE TITLE
AWS EBS volume data is deleted in certain cases

### ISSUE THREAD

**Issue by erulabs** [GoogleCloudPlatform/kubernetes#11012]
Hello!

  Kubernetes sometimes deletes all data from my EBS backed volume. Given a controller like so:

```
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: nginx-store
          mountPath: "/var/nginx"
      volumes:
      - name: nginx-store
        awsElasticBlockStore:
          volumeID: aws://REGION/VOLUME_ID
          fsType: ext4
```

One would expect data in "/var/nginx" to persist, however, it doesn't appear to persist when the pod moves between hosts.

Running `kubectl stop pod nginx-ID` works _most_ of the time, but when the pod moves between hosts I see an event like so:

```
Thu, 09 Jul 2015 20:02:57 +0000   Thu, 09 Jul 2015 20:02:57 +0000   1         nginx-f26t2   Pod                                                         failedSync         {kubelet REDACTED}   Error syncing pod, skipping: Error attaching EBS volume: VolumeInUse: VOLUME_ID is already attached to an instance
                                  status code: 400, request id: []
Thu, 09 Jul 2015 20:02:57 +0000   Thu, 09 Jul 2015 20:02:57 +0000   1         nginx-f26t2   Pod                 failedMount   {kubelet REDACTED}   Unable to mount volumes for pod "nginx-f26t2_default": Error attaching EBS volume: VolumeInUse: VOLUME_ID is already attached to an instance
```

The interesting part is that the EBS volume _does_ re-attach to the system the pod is moving to and it _does_ mount properly - it just has no data in it when it is mounted (as if its been `rm -rf`ed)

I am learning Go and eager to grok the Kubernetes codebase a bit, so I wanted to take a stab (more of a wild guess). My suspicion is this code: https://github.com/GoogleCloudPlatform/kubernetes/blob/530bff315ff034d0c9098004f35f01d26ab40aaa/pkg/cloudprovider/aws/aws.go#L1316-L1322

It seems to me that if we receive an error message we `return`, which prevents us from reaching `waitForAttachmentStatus`. I get the feeling this causes a race wherein the new pod boots up _while_ the volume is being attached. This would account for my seeing this fairly rarely. It seems to me Kubernetes should block the entire pod creation process while it waits for the disk to be mounted to the correct Node. Instead, it sees the AWS failure and continues on its way.

Any thoughts? Thanks for your time!
