### ISSUE TITLE
Externalized service incredibly slow

### ISSUE THREAD

**Issue by bkeroackdsc** [GoogleCloudPlatform/kubernetes#11632]
I have a private Docker registry running as an RC/pod/service within a Kubernetes cluster (v0.21.4) running on CoreOS in AWS. The docker registry is a pod based on the upstream Docker v1 and v2 images behind an nginx proxy container (all standard according to the documentation).

The controller and service are as follows:
```yaml
---

kind: ReplicationController
apiVersion: v1beta3
metadata:
  name: docker.registry
  labels:
    name: docker.registry
spec:
  replicas: 1
  selector:
    name: docker.registry
  template:
    metadata:
      labels:
        name: docker.registry
    spec:
      containers:
        - name: docker-registry-v1
          image: dollarshaveclub/docker-registry-v1:latest
          ports:
            - containerPort: 5001
              protocol: TCP
        - name: docker-registry-v2
          image: dollarshaveclub/docker-registry-v2:latest
          ports:
            - containerPort: 5002
              protocol: TCP
        - name: registry-nginx-proxy
          image: dollarshaveclub/registry-nginx-proxy:latest
          ports:
            - containerPort: 5000
              protocol: TCP
        - name: registry-redis
          image: redis:3.0
          ports:
            - containerPort: 6379
              protocol: TCP
---

kind: Service
apiVersion: v1beta3
metadata:
    name: private-registry
    labels:
        name: private.registry
spec:
    selector:
        name: docker.registry
    type: NodePort
    ports:
        - port: 5000
          nodePort: 30000
          protocol: TCP

```

This service is externalized via an ELB that listens on port 5000 and proxies to all kubernetes minions/nodes on port 30000.

This works great using an internal load balancer accessed via VPN. However on a second public-facing load balancer (set up identically) requests are *incredibly* slow. >60-70 seconds per request! Occasionally I will get a normal response time but the majority of them are so slow as to cause most clients to time out.

I've tried destroy/recreating the ELB (thinking perhaps the problem was the load balancer) as well as destroying and recreating the controller/pods. In all cases, requests originating from the internal network (via VPN) are fast while requests from the public internet are slow.

Any ideas what might be causing this? Flannel or some aspect of kubernetes network routing?
