### ISSUE TITLE
How to change Kubernetes service's node port range?

### ISSUE THREAD

**Issue by pz07** [GoogleCloudPlatform/kubernetes#11690]
When deploying Kubernetes services I get an error: 

```The Service "my-service" is invalid:spec.ports[0].nodePort: spec.ports[0].nodePort: invalid value '2181': provided port is not in the valid range```

This is my service configuration:

```
---
  kind: "Service"
  apiVersion: "v1"
  metadata: 
    name: "my-service"
    labels: 
      name: "my-service"
      component: "my-services"
      version: "0.0.1"
  spec: 
    type: "LoadBalancer"
    sessionAffinity: "ClientIP"
    ports: 
      - 
        name: "port"
        port: 2181
        nodePort: 2181
    selector: 
      name: "my-service"
```

This is on bare metal Kubernetes installation on CoreOS. The very similar installation on CoreOS through Vagrant works as expected. I don't see any configuration item in both master.yaml and node.yaml related to port ranges. 

Any suggestions? 

Version of bare metal installation:

```
kubectl version
Client Version: version.Info{Major:"0", Minor:"21", GitVersion:"v0.21.0", GitCommit:"39b013a5d5fb09b5bb7236b553dfa189f8884bbd", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"19", GitVersion:"v0.19.3", GitCommit:"3103c8ca0f24514bc39b6e2b7d909bbf46af8d11", GitTreeState:"clean"}
```

Version of working Vagrant installation:

```
kubectl version
Client Version: version.Info{Major:"0", Minor:"21", GitVersion:"v0.21.0", GitCommit:"39b013a5d5fb09b5bb7236b553dfa189f8884bbd", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"21", GitVersion:"v0.21.0", GitCommit:"39b013a5d5fb09b5bb7236b553dfa189f8884bbd", GitTreeState:"clean"}
```
