### ISSUE TITLE
IPv4 Expose

### ISSUE THREAD

**Issue by KSanthanam** [GoogleCloudPlatform/kubernetes#11818]
I get this error from my rethinkdb pods
"Failed to connect to host:28015 in less than 20s."

I researched and found that this error happens when the docker exposes the ports under IPV6 instead of IPV4. Can you please tell me how to ensure IPV4 protocol in Kubernetes. I noticed this after upgrading kubernetes.
My current version is
```
Client Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.0", GitCommit:"cd821444dcf3e1e237b5f3579721440624c9c4fa", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"21", GitVersion:"v0.21.4", GitCommit:"3d43944bee17e7147c2ae59aa97a63fb5111d6b0", GitTreeState:"clean"}
```
my rc
-------
```
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    db: rethinkdb
  name: rethinkdb-rc-2.0.4
  namespace: dn
spec:
  replicas: 1
  selector:
    db: rethinkdb
    role: replicas
  template:
    metadata:
      labels:
        db: rethinkdb
        role: replicas
    spec:
      containers:
      - image: gcr.io/dealer-networks/rethinkdb:v2.0.4
        name: rethinkdb
        ports:
        - containerPort: 8080
          name: admin-port
        - containerPort: 28015
          name: driver-port
        - containerPort: 29015
          name: cluster-port
        volumeMounts:
        - mountPath: /rethinkdb
          name: rethinkdb-storage
      volumes:
      - name: rethinkdb-storage
        # This GCE PD must already exist. 
        gcePersistentDisk:
          pdName: "dnetworks-rdb-data"
          fsType: "ext4"
```

my service
-------------
```
apiVersion: v1
kind: Service
metadata:
  labels:
    db: influxdb
  name: rethinkdb-driver
  namespace: dn
spec:
  ports:
    - port: 28015
      targetPort: 28015
  selector:
    db: rethinkdb
```

Thank you in advance.
