### ISSUE TITLE
openshift origin with NodePort service

### ISSUE THREAD

**Issue by Smana** [GoogleCloudPlatform/kubernetes#11862]
Hi,

I have a cluster composed of 3 CoreOS nodes (eg: i'm not using a cloud provider)
I'm trying to test openshift origin as described here : 
https://github.com/GoogleCloudPlatform/kubernetes/pull/9938

What i want to do is to expose the service using the type "NodePort".
>If you set the type field to "NodePort", the Kubernetes master will allocate a port from a flag-configured range (default: 30000-32767), and each node will proxy that port (the same port number on every node) into your Service. That port will be reported in your Service's spec.ports[*].nodePort field.

So i configured the service as follows : 
```
apiVersion: v1
kind: Service
metadata:
  name: openshift
spec:
  ports:
    - port: 8443
      name: openshift
      targetPort: 8443
  selector:
    name: openshift
  type: NodePort
```

From what i understant the service would be redirected from each node of my cluster using the same tcp port.
```
You have exposed your service on an external port on all nodes in your
cluster.  If you want to expose this service to the external internet, you may
need to set up firewall rules for the service port(s) (tcp:31045) to serve traffic.
```
Indeed the iptables rule is created.

So i followed the steps below.
Note that the ip address "10.115.77.87" has been chosen randomly from the ip addresses of the nodes.
```
export OPENSHIFT_EXAMPLE=$(pwd)/examples/openshift-origin
export OPENSHIFT_CONFIG=${OPENSHIFT_EXAMPLE}/config
sudo mkdir ${OPENSHIFT_CONFIG}
sudo /opt/bin/kubectl config view --output=yaml --kubeconfig=/etc/kubernetes/scheduler.kubeconfig --kubeconfig=/etc/kubernetes/kubectl.kubeconfig --kubeconfig=/etc/kubernetes/controller-manager.kubeconfig --flatten=true --minify=true > ${OPENSHIFT_CONFIG}/kubeconfig
sudo /opt/bin/kubectl create -f $OPENSHIFT_EXAMPLE/openshift-service.yaml
sleep 60
```
The config file for openshift is created using the following command
```
export PUBLIC_IP="10.115.77.87"
sudo docker run --privileged -v ${OPENSHIFT_CONFIG}:/config openshift/origin start master --write-config=/config --kubeconfig=/config/kubeconfig --master=https://localhost:8443 --public-master=https://${PUBLIC_IP}:8443
sudo -E chown ${USER} -R ${OPENSHIFT_CONFIG}
```
I can confirm that by checking the output file 
```
head examples/openshift-origin/config/master-config.yaml
apiLevels:
- v1beta3
- v1
apiVersion: v1
assetConfig:
  logoutURL: ""
  masterPublicURL: https://10.115.77.87:8443
  publicURL: https://10.115.77.87:8443/console/
  servingInfo:
    bindAddress: 0.0.0.0:8443
    certFile: master.server.crt
    clientCA: ""
    keyFile: master.server.key
    maxRequestsInFlight: 0
    requestTimeoutSeconds: 0
...
```

Then i when i try to create the secret json
```
sudo docker run -i -t --privileged -e KUBECONFIG=/kubeconfig -v ${HOME}/.kube/config:/kubeconfig -v ${OPENSHIFT_CONFIG}:/config openshift/origin cli secrets new openshift-config /config -o json &> ${OPENSHIFT_EXAMPLE}/secret.json
error: couldn't read version from server: Get https://localhost:8443/api: dial tcp 127.0.0.1:8443: connection refused

see 'openshift cli secrets new -h' for help.
```

This output says it tries to connect to the socket localhost:8443 but there is not such service.
I guess there's something i don't understand.
Could you please help me ?

Regards,
Smana

**Comment by smarterclayton** [comment]
It looks like the command isn't finding your kubeconfig file.  On the last line, instead of running "secrets new ..." run "config view" which should print the config the client thinks it has (from KUBECONFIG).  If that config is pointing to 127.0.0.1 or localhost then the secrets new command won't be able to see the Kube master.

**Comment by Smana** [comment]
@smarterclayton 
Yes, it seems that my configuration is wrong.
```
sudo docker run -it --privileged -e="KUBECONFIG=/config/admin.kubeconfig" -v ${OPENSHIFT_CONFIG}:/config openshift/origin cli config view                                 
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REDACTED
    server: https://:8443
  name: :8443
- cluster:
    certificate-authority-data: REDACTED
    server: https://localhost:8443
  name: localhost:8443
contexts:
- context:
    cluster: :8443
    namespace: default
    user: system:admin/localhost:8443
  name: default/:8443/system:admin
- context:
    cluster: localhost:8443
    namespace: default
    user: system:admin/localhost:8443
  name: default/localhost:8443/system:admin
current-context: default/localhost:8443/system:admin
kind: Config
preferences: {}
users:
- name: system:admin/localhost:8443
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```
I need to figure out where i'm mistaken.

here is my kubeconfig : 
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTZrS3hmNVlYbEo4QjB4RkdXUDFqdmVoN0......ZmYkUKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://10.115.77.86:443
  name: coreos.com
contexts:
- context:
    cluster: coreos.com
    user: controller-manager
  name: controller-manager-to-coreos.com
current-context: controller-manager-to-coreos.com
kind: Config
preferences: {}
users:
- name: controller-manager
  user:
    token: Imn00SGKQul....
```
Regards,
Smana

**Comment by smarterclayton** [comment]
Hrm - try running an entrypoint /bin/bash but with the other env and
arguments.  Then look to make sure the kubeconfig from outside is at the
right location inside.  That'll at least track down why the binary in the
container isn't seeing the correct file.  You'll need the correct
kubeconfig inside the container.  Check the env in the running container
(maybe the external env var isn't overriding the KUBECONFIG saved with the
image (which defaults to a different directory).

On Jul 25, 2015, at 3:47 PM, Smana <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton>
Yes, it seems that my configuration is wrong.

sudo docker run -it --privileged
-e="KUBECONFIG=/config/admin.kubeconfig" -v
${OPENSHIFT_CONFIG}:/config openshift/origin cli config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REDACTED
    server: https://:8443
  name: :8443
- cluster:
    certificate-authority-data: REDACTED
    server: https://localhost:8443
  name: localhost:8443
contexts:
- context:
    cluster: :8443
    namespace: default
    user: system:admin/localhost:8443
  name: default/:8443/system:admin
- context:
    cluster: localhost:8443
    namespace: default
    user: system:admin/localhost:8443
  name: default/localhost:8443/system:admin
current-context: default/localhost:8443/system:admin
kind: Config
preferences: {}
users:
- name: system:admin/localhost:8443
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED

I need to figure out where i'm mistaken.

here is my kubeconfig :

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data:
LS0tLS1CRUdJTZrS3hmNVlYbEo4QjB4RkdXUDFqdmVoN0......ZmYkUKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://10.115.77.86:443
  name: coreos.com
contexts:
- context:
    cluster: coreos.com
    user: controller-manager
  name: controller-manager-to-coreos.com
current-context: controller-manager-to-coreos.com
kind: Config
preferences: {}
users:
- name: controller-manager
  user:
    token: Imn00SGKQul....

Regards,
Smana

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/11862#issuecomment-124880170>
.

**Comment by hingstarne** [comment]
```error: couldn't read version from server: Get https://localhost:8443/api: dial tcp 127.0.0.1:8443: connection refused```
As the secrets creation should not need a up and running openshiftmaster , when the -o flag is given, this is maybe a bug in the openshift cli? 
If you just want a result you could use the the kubernetes config file from your running kubernetes master instead. Don´t know where you have it in your installation.

**Comment by Smana** [comment]
@smarterclayton 
Thank you, i did what you suggested: 
```
docker run -it --privileged -e="KUBECONFIG=/config/admin.kubeconfig" -v ${OPENSHIFT_CONFIG}:/config --entrypoint=/bin/bash openshift/origin
```
And i noticed that i wasn't giving the right config file.
Then i fixed my command line as follows and i successfully created the secret.json file
```
sudo docker run -it --privileged -e="KUBECONFIG=/config/kubeconfig" -v ${OPENSHIFT_CONFIG}:/config openshift/origin cli secrets new openshift-config /config -o json &> ${OPENSHIFT_EXAMPLE}/secret.json
```

Unfortunately i still have a problem after creating the rc.
```
kubectl get secret          
NAME                  TYPE                                  DATA
openshift-config      Opaque                                28
```

The pods is not flagged as ready and i don't understand why
```
kubectl get pods
NAME                 READY     STATUS    RESTARTS   AGE
openshift-0wlkc      0/1       Running   12         13m
```
I can see the following logs
```
kubectl logs openshift-0wlkc
W0725 21:31:01.134038       1 start_master.go:251] serviceAccountConfig.publicKeyFiles: invalid value '': no service account tokens will be accepted by the API, which will prevent builds and deployments from working
I0725 21:31:01.134304       1 start_master.go:308] Starting OpenShift master on 0.0.0.0:8443 (v1.0.3-54-g4f75331)
I0725 21:31:01.134595       1 start_master.go:309] Public master address is https://:8443
```

The service should be reachable on each node with the tcp port 31045
```
kubectl describe service openshift
Name:			openshift
Namespace:		default
Labels:			<none>
Selector:		name=openshift
Type:			NodePort
IP:			10.253.36.184
Port:			openshift	8443/TCP
NodePort:		openshift	31045/TCP
Endpoints:		<none>
Session Affinity:	None
No events.
```

the iptables rule is set
```
sudo iptables -nL -t nat | egrep '(31045|8443)'
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            /* default/openshift:openshift */ tcp dpt:31045 redir ports 33962
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            /* default/openshift:openshift */ tcp dpt:31045 to:10.115.77.89:33962
REDIRECT   tcp  --  0.0.0.0/0            10.253.36.184        /* default/openshift:openshift */ tcp dpt:8443 redir ports 33962
DNAT       tcp  --  0.0.0.0/0            10.253.36.184        /* default/openshift:openshift */ tcp dpt:8443 to:10.115.77.89:33962
```

I still don't understand how to reach the openshift ui : 
```
wget https://10.115.77.87:31045
--2015-07-25 21:39:03--  https://10.115.77.87:31045/
Connecting to 10.115.77.87:31045... connected.
Unable to establish SSL connection.
```

Thank you all for your answers,
Smana

**Comment by hingstarne** [comment]
could you try to port-forward the ui?
kubectl port-forward -p openshift-0wlkc 8443
and access the ui via curl -k https://localhost:8443 ?

**Comment by Smana** [comment]
Hi @hingstarne 
I think the pod is not created properly : 
```
kubectl port-forward -p openshift-0wlkc 8443
I0726 07:13:16.459016   13404 portforward.go:225] Forwarding from 127.0.0.1:8443 -> 8443
I0726 07:13:16.459900   13404 portforward.go:225] Forwarding from [::1]:8443 -> 8443
I0726 07:13:54.286703   13404 portforward.go:251] Handling connection for 8443
E0726 07:13:54.327331   13404 portforward.go:310] An error occurred forwarding 8443 -> 8443: Error forwarding port 8443 to pod openshift-0wlkc_default, uid : Unable to do port forwarding: socat not found.
```

```
curl -k http://localhost:8443
curl: (52) Empty reply from server
```

And the container is not "ready" from what i see there ?
```
kubectl get pods
NAME                 READY     STATUS    RESTARTS   AGE
openshift-0wlkc      0/1       Running   10         9h
```

**Comment by Smana** [comment]
When i do a "kubectl describe pod ..." i get the following error regarding a secret missing : 
```
  Sun, 26 Jul 2015 08:20:16 +0000	Sun, 26 Jul 2015 08:20:16 +0000	1	{scheduler }				scheduled		Successfully assigned openshift-1wvlr to 10.115.77.88
  Sun, 26 Jul 2015 08:20:16 +0000	Sun, 26 Jul 2015 08:24:57 +0000	29	{kubelet 10.115.77.88}			failedSync		Error syncing pod, skipping: secrets "default-dockercfg-33q38" not found
```

Indeed this secret doesn't appear : 
```
kubectl get secret
NAME                   TYPE                                  DATA
builder-token-w31lz    kubernetes.io/service-account-token   2
default-token-kouws    kubernetes.io/service-account-token   2
deployer-token-gsal4   kubernetes.io/service-account-token   2
openshift-config       Opaque                                28
```

I've done all the steps again and again and it still look for the same secret named "default-dockercfg-33q38".
How can i get rid of this secret ?

Note that i've been able to create the pod properly once but my configuration wasn't good.
My ${PUBLIC_IP}:${NODE_PORT} must match the one exposed with NodPort
```
sudo docker run --privileged -v ${OPENSHIFT_CONFIG}:/config openshift/origin start master --write-config=/config --kubeconfig=/config/kubeconfig --master=https://localhost:8443 --public-master=https://${PUBLIC_IP}:${NODE_PORT}
```

Now i'm just trying to clean up everything and redo the steps

Regards,
Smana

**Comment by Smana** [comment]
Ok i've rebuilt the cluster from scratch then i followed the steps again:
1 - change the openshift-service.yaml file in order to set "NodePort" instead of "LoadBalancer"
```
apiVersion: v1
kind: Service
metadata:
  name: openshift
spec:
  ports:
    - port: 8443
      name: openshift
      targetPort: 8443
  selector:
    name: openshift
  type: NodePort
```
2 - Create the service
```
export OPENSHIFT_EXAMPLE=$(pwd)/examples/openshift-origin
export OPENSHIFT_CONFIG=${OPENSHIFT_EXAMPLE}/config
sudo mkdir ${OPENSHIFT_CONFIG}
sudo /opt/bin/kubectl config view --output=yaml --kubeconfig=/etc/kubernetes/scheduler.kubeconfig --kubeconfig=/etc/kubernetes/kubectl.kubeconfig --kubeconfig=/etc/kubernetes/controller-manager.kubeconfig --flatten=true --minify=true > ${OPENSHIFT_CONFIG}/kubeconfig
sudo /opt/bin/kubectl create -f $OPENSHIFT_EXAMPLE/openshift-service.yaml
```

3 - get the tcp port exposed. In the following example the console will be reachable using tcp port 31844
```
mkdir: cannot create directory '/home/core/kubernetes/examples/openshift-origin/config': File exists
You have exposed your service on an external port on all nodes in your
cluster.  If you want to expose this service to the external internet, you may
need to set up firewall rules for the service port(s) (tcp:31844) to serve traffic.
```

4 - use the tcp port and a node ip for the remaining steps
```
export NODE_IP="10.115.77.87"
export NODE_PORT="31844
sudo docker run --privileged -v ${OPENSHIFT_CONFIG}:/config openshift/origin start master --write-config=/config --kubeconfig=/config/kubeconfig --master=https://localhost:8443 --public-master=https://${NODE_ID}:${NODE_PORT}
sudo -E chown ${USER} -R ${OPENSHIFT_CONFIG}
sudo docker run -it --privileged -e="KUBECONFIG=/config/kubeconfig" -v ${OPENSHIFT_CONFIG}:/config openshift/origin cli secrets new openshift-config /config -o json &> ${OPENSHIFT_EXAMPLE}/secret.json
sudo /opt/bin/kubectl create -f ${OPENSHIFT_EXAMPLE}/secret.json
sudo /opt/bin/kubectl create -f ${OPENSHIFT_EXAMPLE}/openshift-controller.yaml
```
The console is now reachable from any of my nodes. Now i have to figure out the default login/pass and to set up a loadbalancer (haproxy) in front of my nodes in order to have a real public ip.

Thank you all for your help
Regards,
Smana
