### ISSUE TITLE
Volume does not bind on RC when pod dies

### ISSUE THREAD

**Issue by pmoncadaisla** [GoogleCloudPlatform/kubernetes#11974]
Hi,

I'm currently running Kubernetes on GCE.
I have a replication controller for a MySQL service, this is the YAML file:

```
kind: "ReplicationController"
apiVersion: "v1"
metadata: 
  name: "mysql-controller"
  labels: 
    state: "serving"
spec: 
  replicas: 1
  selector: 
    app: "mysql"
  template: 
    metadata: 
      labels: 
        app: "mysql"
        name: "mysql"
    spec: 
      volumes:
        - name: mysql-persistent-storage
          gcePersistentDisk:
            # This GCE PD must already exist.
            pdName: mysql-disk
            fsType: ext4
      containers:
        - resources:
            limits :
              cpu: 0.5
          image: mysql
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              # change this
              value: mysql
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
              # name must match the volume name below
            - name: mysql-persistent-storage
              # mount path within the container
              mountPath: /var/lib/mysql
      restartPolicy: "Always"
      dnsPolicy: "ClusterFirst"
```

The first time the pod is created by the replication controller, everything works fine, the disk is mounted on the host and binded to the container.
If the pod dies, and the replication controller attemps to create a new pod, the pod is created (and running) but "it forgets" about the volume.

Are we doing something wrong?
Is this the spected behaviour?

Thank!
