### ISSUE TITLE
Consider making namespace support more internally consistent

### ISSUE THREAD

**Issue by DreadPirateShawn** [GoogleCloudPlatform/kubernetes#12039]
Currently namespaces are supported inconsistently -- that is, they can be used without actually being created, leading to a scenario where they appear to be working except tangential features don't behave correctly.

Specifically, a pod / rc can be created which uses an undefined namespace:
```
apiVersion: v1
kind: ReplicationController
id: foo
metadata:
  name: foo1
  namespace: bar
  labels:
    name: foo
spec:
  replicas: 1
  selector:
    name: foo
    version: v1
  template:
    metadata:
      labels:
        name: foo
        version: v1
    spec:
      containers:
        - name: foo
          image: fooimage:latest
```

```
$ kubectl --namespace=bar create -f my-controller.yaml
```

```
$ kubectl get pods
NAME      READY     STATUS    RESTARTS   AGE
$ kubectl --namespace=bar get pods
NAME      READY     STATUS    RESTARTS   AGE
foo       1/1       Running   0          2h
```

However, despite the namespace appearing to work, the namespace does not actually exist:
```
$ kubectl get namespaces
NAME        LABELS    STATUS
default     <none>    Active

$ curl http://10.0.0.2:8080/api/v1/namespaces
{
  "kind": "NamespaceList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/namespaces",
    "resourceVersion": "828840"
  },
  "items": [
    {
      "metadata": {
        "name": "default",
        "selfLink": "/api/v1/namespaces/default",
        "uid": "2a67494e-1e7c-11e5-aa49-00505629c58f",
        "resourceVersion": "13",
        "creationTimestamp": "2015-06-29T16:30:34Z"
      },
      "spec": {
        "finalizers": [
          "kubernetes"
        ]
      },
      "status": {
        "phase": "Active"
      }
    }
  ]
}
```

This causes unexpected downstream impact on (for instance) heapster, which ignores data for pods that have an unrecognized namespace.

The fix is to create the namespace officially, eg:

```
apiVersion: v1
kind: Namespace
metadata:
  name: bar
```
```
$ kubectl.sh create -f kube-namespace.yaml

$ kubectl.sh get namespaces
NAME        LABELS    STATUS
bar         <none>    Active
default     <none>    Active
```

The request is to fix the internal disconnect, such that a namespace's visibility and usability remain in sync -- either creating a pod with a namespace implicitly generates said namespace object, or a namespace should not be usable at all without officially creating it. (Attempting to create the rc / pod with namespace "bar" should throw an error if namespace "bar" has not been created, rather than succeeding and appearing to work as expected, until subtle downstream impact is discovered later.)
