### ISSUE TITLE
Print clear error when same RC is provided for both arguments in kubectl rollingupdate 

### ISSUE THREAD

**Issue by jasonkuhrt** [GoogleCloudPlatform/kubernetes#3458]
I believe the problem is that `kubectl rollingupdate` requires a schema of `v1beta3` but that `0.8.0` Kubernetes does not have the ability to handle that schema yet. I just want to confirm this is true however.

So with a schema like:

```yaml
kind: ReplicationController
apiVersion: v1beta2
id: cloud-delivery-test
labels:
  name: cloud-delivery-test
  version: 0.5.0
desiredState:
  replicas: 2
  replicaSelector:
    name: cloud-delivery-test
    version: 0.5.0
  podTemplate:
    labels:
      name: cloud-delivery-test
      version: 0.5.0
    desiredState:
      manifest:
        version: v1beta1
        containers:
        - name: cloud-delivery-test
          image: quay.io/littlebits/cloud-delivery-test:latest
          ports:
          - name: cloud-delivery-test
            containerPort: 7654
          env:
          - name: PORT
            value: 7654
```
It fails when used like so:

```
⧑  kubectl rollingupdate cloud-delivery-test -f kubernetes-v1beta2/replicationController.yaml                                                      

Continuing update with existing controller cloud-delivery-test.
F0113 23:31:57.503427   57607 rollingupdate.go:99] Missing/unexpected annotations for controller cloud-delivery-test: map[]
```

If I try a `v1beta3` schema that looks like:

```yaml
kind: ReplicationController
apiVersion: v1beta3
metadata:
  name: cloud-delivery-test
  labels:
    name: cloud-delivery-test
    version: 0.5.0
spec:
  replicas: 2
  selector:
    name: cloud-delivery-test
    version: 0.5.0
  template:
    metadata:
      labels:
        name: cloud-delivery-test
        version: 0.5.0
    spec:
      containers:
      - name: cloud-delivery-test
        image: quay.io/littlebits/cloud-server-delivery-test
        ports:
        - name: cloud-delivery-test
          containerPort: 7654
        env:
        - name: PORT
          value: 7654
```

then the error is:

```
⧑ kubectl rollingupdate cloud-delivery-test -f kubernetes-v1beta3/replicationController.yaml                                                      

F0114 09:43:17.497021   58006 resource.go:302] no object named "ReplicationController" is registered
```

The error generation comes from: https://github.com/GoogleCloudPlatform/kubernetes/blob/6e242739378fd830a62afb1375c80ad24254a85b/pkg/kubectl/rolling_updater.go#L154-L155

Am I correct that it is impossible to use the `kubectl rollingupdate` command against `0.8.0`?
