### ISSUE TITLE
Job submissions can break functionality of "kubectl get pods"

### ISSUE THREAD

**Issue by jayunit100** [GoogleCloudPlatform/kubernetes#3461]
Submitting a incorrect yaml file for kubectl creation breaks the "get pods" command, somehow... This is obviously a bug since a user's submission error shouldn't result in an inability to view status of the existing pods.

*DETAILS* 

the following yaml

```
 cat spk-kube.yaml 
id: spk
kind: Pod
apiVersion: v1beta1
desiredState:
  manifest:
    version: v1beta1
    id: spark
    containers:
      - name: spk
        image: spk
        cpu: 1000
        ports:
          - name: sp
            containerPort: 7077
labels:
  name: spk
```

if launched w / `kube create -f ...` will cause `kubectl get pods` to report the following error message.

*get.go:75] The string provided is not a valid PodPhase constant value*
