### ISSUE TITLE
git volume should clone the repo at the root of the volume

### ISSUE THREAD

**Issue by proppy** [GoogleCloudPlatform/kubernetes#3563]
Currently they add an extra directory named after the repo, so:
```
    volumes:
    - name: content
      source:
        gitRepo:
          repository: https://github.com/proppy/foo.git
```
Would result into
```
/var/lib/kubelet/pod-name/volumes/git/content/foo/.git
```
instead of 
```
/var/lib/kubelet/pod-name/volumes/git/content/.git
```
