### ISSUE TITLE
Kubelet in standalone doesn't work with example YAML files

### ISSUE THREAD

**Issue by filbranden** [GoogleCloudPlatform/kubernetes#3584]
I'm trying containervm with kubelet built from head and this YAML file:

https://cloud.google.com/compute/docs/containers/container_vms#create_the_manifest

The YAML file is v1beta2 and doesn't set a name to the Pod. When starting kubelet, it doesn't start the "nc" echo server and complains about this on the logs:

```
config.go:307] Pod[1] (<empty-name>.url-a75326da) from http failed validation, ignoring: name: required value ''
```

Chatting with @dchen1107 on IM she mentioned it might be due to a change from @thockin that now requires non-empty pod names (replaces random generation with validation for non-emptiness) but that means all existing YAML files (even the ones with an older version) will stop working... Is that expected?

Thanks!
Filipe

**Comment by dchen1107** [comment]
Yes, the latest kubelet call validation on all sources: etcd, file, http, etc. now, and PodName is a required field. One potential fix for this is also invoke conversion code before call validation, like what we have done at apiserver. 

Thoughts? @thockin

**Comment by filbranden** [comment]
Just so I get unblocked... Do you have an example YAML file that will set the pod name and will work?

Right now this is what I'm using:

```
version: v1beta2
containers:
  - name: simple-echo
    image: busybox
    command: ['nc', '-p', '8080', '-l', '-l', '-e', 'echo', 'hello world!']
    ports:
      - name: nc-echo
        hostPort: 8080
        containerPort: 8080
```

Should I bump up version to v1beta3 and include a new `- pod: whatever` field somewhere?

Thanks!
Filipe
