### ISSUE TITLE
Unable to pull new image from private repository

### ISSUE THREAD

**Issue by jasonkuhrt** [GoogleCloudPlatform/kubernetes#4009]
There is something wrong, somewhere, with my deployment pipeline of a pod to kubernetes, and after a few hours of attempts, the fault seems to live with Kubernetes.

```
⧑ kubectl version                                                                                                                                                                                                                                                 

Client Version: version.Info{Major:"0", Minor:"9+", GitVersion:"v0.9.0-389-gaf25c3c671d592", GitCommit:"af25c3c671d592bf8643d65d24fb8b37b3aec994", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"9+", GitVersion:"v0.9.2-dirty", GitCommit:"013a97ea6e2a143f763035defdbcbcdc1b6d3411", GitTreeState:"dirty"}
```

I change project code such that I will see some logs. I first build:
```
docker build --tag gcr.io/littlebits_electronics/cloud-api-stream:latest .
```


Then I test my app locally to make sure the logs are in place:
```
⧑ docker run gcr.io/littlebits_electronics/cloud-api-stream:latest                                                                                                                                                                                                

> cloud-server-api-stream@0.2.12 start /usr/src/app
> node lib/index

{ iknowhttpsisbetter: true, port: 7200 }
dev
7200
```
Sure enough, the last three lines above demonstrate the logging is working. Ok.


Now I want to deploy to my GKE Kubernetes cluster. I upload the image:
```
⧑ gcloud preview docker push gcr.io/littlebits_electronics/cloud-api-stream:latest

The push refers to a repository [gcr.io/littlebits_electronics/cloud-api-stream] (len: 1)
Sending image list
Pushing repository gcr.io/littlebits_electronics/cloud-api-stream (1 tags)
Image 511136ea3c5a already pushed, skipping
Image bce696e097dc already pushed, skipping
Image 58052b122b60 already pushed, skipping
Image 81c86d8c1e0c already pushed, skipping
Image 3a20d8faf171 already pushed, skipping
Image c7a7a01d634e already pushed, skipping
Image 2a13c2a76de1 already pushed, skipping
Image 4cc808131c54 already pushed, skipping
Image bf2afba3f5e4 already pushed, skipping
Image 0cba665db8d0 already pushed, skipping
Image 322af6f234b2 already pushed, skipping
Image 9787c55efe92 already pushed, skipping
Image 1bb70ea16cde already pushed, skipping
Image 5b84aff4e456 already pushed, skipping
Image 0bbfa99418ff already pushed, skipping
Image 6cbe0614a395 already pushed, skipping
Image 0351de8ed211 already pushed, skipping
Image b9a9ca84f62d already pushed, skipping
Image 385f68383f91 already pushed, skipping
Image 57df6ccff2f5 already pushed, skipping
Image da85e1210d1a already pushed, skipping
Image 71dd0a045d0a already pushed, skipping
Image 9bd5536d1178 already pushed, skipping
Image f9cf59b7f7c5 already pushed, skipping
Pushing tag for rev [f9cf59b7f7c5] on {https://gcr.io/v1/repositories/littlebits_electronics/cloud-api-stream/tags/latest}
```
Followed by launching a new `ReplicationController` which looks like this:
```
⧑ cat kubernetes/rc.yaml                                                                                                                                                                                                                                          

kind: ReplicationController
apiVersion: v1beta1
id: cloud-api-stream
desiredState:
  labels:
    name: cloud-api-stream
  replicas: 1
  replicaSelector:
    name: cloud-api-stream
  podTemplate:
    labels:
      name: cloud-api-stream
    desiredState:
      manifest:
        version: v1beta1
        id: cloud-api-stream
        containers:
          - name: cloud-api-stream
            image: gcr.io/littlebits_electronics/cloud-api-stream:latest
            ports:
              - name: cloud-api-stream
                containerPort: 7200
            env:
              - name: NODE_ENV
                value: stage
```
```
⧑ kubectl create -f kubernetes/rc.yaml                                                                                                                                                                                                                            

cloud-api-stream
```

When I inspect logs for pod no-dice... its an old error that should be long-gone:
```
⧑ kubectl log c77f775a-a96d-11e4-bfb6-42010af0101c                                                                                                                                                                                                                

2015-01-31T19:21:41.361180553Z
2015-01-31T19:21:41.361180553Z > cloud-server-api-stream@0.2.12 start /usr/src/app
2015-01-31T19:21:41.361180553Z > node lib/index
2015-01-31T19:21:41.361180553Z
2015-01-31T19:21:41.448201504Z
2015-01-31T19:21:41.448658094Z /usr/src/app/node_modules/primus/node_modules/create-server/index.js:62
2015-01-31T19:21:41.448958775Z     throw new Error('Missing the SSL key or certificate files in the options.'
```

kubectl get pods shows this which I feel may point to an error (see how the tag is `0.2.12` instead of `latest`
```
⧑ kubectl get pods --selector='name=cloud-api-stream'                                                                                                                                                                                                             

POD                                    IP                  CONTAINER(S)        IMAGE(S)                                                HOST                                                                        LABELS                  STATUS
c77f775a-a96d-11e4-bfb6-42010af0101c   10.20.2.13          cloud-api-stream    gcr.io/littlebits_electronics/cloud-api-stream:0.2.12   k8s-littlecloud-3-node-3.c.littlebits-electronics.internal/104.154.40.252   name=cloud-api-stream   Running
```

**Comment by jasonkuhrt** [comment]
I've tried this dozens of times, using explicit tag deploys (`0.2.13` etc.) and forcing `imagePullPolicy: PullAlways`

**Comment by jasonkuhrt** [comment]
This seems related to my issue https://github.com/GoogleCloudPlatform/kubernetes/issues/3028 but unlike there the `:latest` tag doesn't do anything for me.

**Comment by jasonkuhrt** [comment]
so now I have a case that looks like a blatant bug:

Given this `ReplicationController` manifest:

```
⧑ cat kubernetes/rc.yaml                                                                                                                                                                                                                                           

kind: ReplicationController
apiVersion: v1beta1
id: cloud-api-stream
desiredState:
  labels:
    name: cloud-api-stream
  replicas: 1
  replicaSelector:
    name: cloud-api-stream
  podTemplate:
    labels:
      name: cloud-api-stream
    desiredState:
      manifest:
        version: v1beta1
        id: cloud-api-stream
        containers:
          - name: cloud-api-stream
            image: gcr.io/littlebits_electronics/cloud-api-stream:0.2.16
            imagePullPolicy: PullAlways
            ports:
              - name: cloud-api-stream
                containerPort: 7200
            env:
              - name: NODE_ENV
                value: stage
```

Use it:

```
⧑ kubectl create -f kubernetes/rc.yaml                                                                                                                                                                                                                             

cloud-api-stream
```

And the container version (docker tag) is launched...:

```
⧑ kubectl get pods -l name=cloud-api-stream                                                                                                                                                                                                                        

POD                                    IP                  CONTAINER(S)        IMAGE(S)                                                HOST                                                                        LABELS                  STATUS
c77f775a-a96d-11e4-bfb6-42010af0101c   10.20.2.13          cloud-api-stream    gcr.io/littlebits_electronics/cloud-api-stream:0.2.12   k8s-littlecloud-3-node-3.c.littlebits-electronics.internal/104.154.40.252   name=cloud-api-stream   Running
```

(And of course the same error as above when I log the pod)

**Comment by pires** [comment]
I think cloud registry is caching so probably some bug.

Try ssh'ing intominions and force remove image;
```
docker rmi -f gcr.io/littlebits_electronics/cloud-api-stream:0.2.16
```

**Comment by jasonkuhrt** [comment]
@pires Thanks.

In my three-node cluster I found that my image had only been downloaded into one node. That node showed the following:

```
⧑ gcloud compute ssh k8s-littlecloud-3-node-3                                                                                                                                                                                                                      [...]

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
jasonkuhrt@k8s-littlecloud-3-node-3:~$ sudo docker images
REPOSITORY                                       TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
gcr.io/littlebits_electronics/cloud-api-stream   0.2.12              1d97fb722fc7        17 hours ago        741.7 MB
gcr.io/littlebits_electronics/cloud-api-stream   0.2.13              54178fdc35bd        20 hours ago        741.7 MB
```

After removing that I tried another deploy of `0.2.16` and sure enough:

```
⧑ kubectl log 7f6e2cf6-a9af-11e4-bfb6-42010af0101c                                                                                                                                                                                                                 
2015-02-01T01:14:12.414855489Z
2015-02-01T01:14:12.414855489Z > cloud-server-api-stream@0.2.16 start /usr/src/app
2015-02-01T01:14:12.414855489Z > node lib/index
2015-02-01T01:14:12.414855489Z
2015-02-01T01:14:12.528305139Z { port: 7200, iknowhttpsisbetter: true }
2015-02-01T01:14:12.530204456Z stage
2015-02-01T01:14:12.530404033Z 7200
2015-02-01T01:14:12.620259872Z {"name":"app","hostname":"7f6e2cf6-a9af-11e4-bfb6-42010af0101c","pid":15,"component":"auth","level":30,"msg":"loaded","time":"2015-02-01T01:14:12.619Z","v":0}
2015-02-01T01:14:12.957343457Z {"name":"app","hostname":"7f6e2cf6-a9af-11e4-bfb6-42010af0101c","pid":15,"component":"wsserver","level":30,"config":{"oauth":{"auth_token_uri":"http://eng-stg1.littlebits.cc/access_tokens","auth_uri":"http://eng-stg1.littlebits.cc/oauth/authorize"},"env":"stage","port":7200,"log_level":"debug","cloudsetup_uri":"http://eng-stg1.cloudsetup.cc","api_http_uri":"https://api-http-stage.littlebitscloud.cc","redis":{"port":11042,"host":"sprightly-daffodil-608.redisgreen.net","password":"4ca32f67b1a345df9ddfc7bd046f4815"}},"msg":"Launching","time":"2015-02-01T01:14:12.957Z","v":0}
```

So we've seen how to work-around this issue at least in one case. If I have any more info I'll report it, and let me know what else would help to debug this issue.

**Comment by pires** [comment]
@thockin and I are really interested in having some sort of proxy that caches locally and this can be an issue.

**Comment by jasonkuhrt** [comment]
@pires @thockin in general:

1. A choice of tool for caching or a generic API that vendors can enable cache on top of (Kubernetes has already baked in tools such as cAdvisor so maybe a cache could be baked in too...)
2. An API for cache-busting. In the case of GKE+GCR a push to the GCR would break the cache of any same-tagged thing

Seems non-trivial at best. Cache is notoriously tricky, lots of potential edge-cases/bugs without a good thorough system in place, and then some.

**Comment by pires** [comment]
Needs some debugging to understand what's going on - sometimes docker is PITA!

**Comment by thockin** [comment]
I agree that cache eviction is hard, and it is a great point.  Docker's
index/registry split might prevent this?  First we have to go to the index
to get hashes for layers then we pull layers.  The index transaction should
not be cached.

**Comment by mbforbes** [comment]
@jasonkuhrt I can't seem to reproduce this, but I might not be taking the exact same steps you are.

Given that you first create a replication controller with an older version, then create a replication controller pointing to a newer version (I'm thinking specifically of your `0.2.16` vs `0.2.12` example above), how are you getting rid of the first one? Scheduling the same replication controller again errors with "replicationController <id> already exists" so I assume you're taking it down with something like `kubectl delete rc <id>`.

If you can give steps that I can take to repro I am more thn happy to look into this further. Trying what seems to be the same process myself, the correctly tagged container gets scheduled.

**Comment by jasonkuhrt** [comment]
@mbforbes Yes I was just deleting like you say, `kubectl delete rc cloud-api-stream`.

**Comment by mbforbes** [comment]
+cc @jlowdermilk 

OK @jasonkuhrt stick with me here, I have a hypothesis for what might have happened. Let me know if any of this doesn't check out. Let's use `v1` as an old tag and `v2` as a new tag in this scenario.

0. `docker build --tag gcr.io/littlebits_electronics/cloud-api-stream:v1 .`
   `gcloud preview docker push gcr.io/littlebits_electronics/cloud-api-stream:v1`

   We build `v1`, tag it, and push it to the private registry.

0. `kubectl create rc.yaml`

   We launch pods at `v1` using a replication controller. It creates `v1` pods with the label `cloud-api-stream`. Here's a snippet of the relevant part of the replication controller YAML file:

   ```yaml
desiredState:
  replicaSelector:
    name: cloud-api-stream
  podTemplate:
    labels:
      name: cloud-api-stream
    desiredState:
      manifest:
        containers:
          - image: gcr.io/littlebits_electronics/cloud-api-stream:v1
   ```

0. `kubectl delete rc cloud-api-stream`

   We delete the replication controller. _However, the `v1` pods still live._

0. `docker build --tag gcr.io/littlebits_electronics/cloud-api-stream:v2 .`
   `gcloud preview docker push gcr.io/littlebits_electronics/cloud-api-stream:v2`

   We build `v2`, tag it, and push it to the private registry.

0. `kubectl create rc.yaml`

   We launch using an updated replication controller; here's the relevant snippet from the YAML file:

   ```yaml
desiredState:
  replicaSelector:
    name: cloud-api-stream
  podTemplate:
    labels:
      name: cloud-api-stream
    desiredState:
      manifest:
        containers:
          - image: gcr.io/littlebits_electronics/cloud-api-stream:v2
   ```

   Note the `v2` tag.

0. The new replication controller uses its `replicaSelector` with the label `cloud-api-stream` and, lo and behold, it finds pods running that match! It doesn't care that those pods are `v1` and the pods that it would create are `v2`; it operates by labels only, and it found sufficient pods with the correct `cloud-api-stream` label that it thinks its job is done.

   If we inspect the pods, we see `v1` pods running, and if we inspect the replication controllers, we see it is apparently trying to maintain `v2` pods, hence the confusion.

Is it possible that this is what happened with your scenario? (On a related note, @zmerlynn and @jlowdermilk mentioned that `rollingupdate` would be the command we'd want in this situation to get the behavior we expect.)
