### ISSUE TITLE
"readOnly must be true" even if replicas is 1

### ISSUE THREAD

**Issue by jasonkuhrt** [GoogleCloudPlatform/kubernetes#4052]
I am getting this error:

```
F0202 22:33:22.114793   23129 create.go:78] replicationController "elasticsearch-data" is invalid: spec.template.spec.volumes.GCEPersistentDisk.ReadOnly: invalid value 'false': must be true
```
```
id: elasticsearch-data
kind: ReplicationController
apiVersion: v1beta1
desiredState:
  replicas: 1
  replicaSelector:
    component: elasticsearch
    role: data
  podTemplate:
    labels:
      component: elasticsearch
      role: data
    desiredState:
      manifest:
        version: v1beta1
        id: elasticsearch-data
        volumes:
          - name: es-persistent-storage
            source:
              persistentDisk:
                pdName: elasticsearch-data
                fsType: ext4
        containers:
          - name: elasticsearch-data
            image: pires/elasticsearch:data
            ports:
              - name: transport
                containerPort: 9300
            volumeMounts:
              - name: es-persistent-storage
                mountPath: /data
```

I've never seen this before, and my understanding is that a `persistentDisk` can be read-and-write... that is the default after all.
