### ISSUE TITLE
Service is not exported after updating Pod's container image

### ISSUE THREAD

**Issue by kazegusuri** [GoogleCloudPlatform/kubernetes#4239]
I'm trying to update Pod to upgrade a container image to the newer one, but it seems Service environment variables are not exported into the new container. I use kubernetes `v0.10.0`.

```
$ kubectl create -f redis.yml
redis-master

$ kubectl get po
POD                 IP                  CONTAINER(S)        IMAGE(S)            HOST                        LABELS              STATUS
redis-master        10.244.95.12        master              dockerfile/redis    172.17.8.102/172.17.8.102   name=redis-master   Running

$ ssh node-01 "docker inspect ca0b5f5364d4" | jq '.[].Config.Env'
[
  "KUBERNETES_SERVICE_HOST=10.244.127.250",
  "KUBERNETES_SERVICE_PORT=443",
  "KUBERNETES_PORT=tcp://10.244.127.250:443",
  "KUBERNETES_PORT_443_TCP=tcp://10.244.127.250:443",
  "KUBERNETES_PORT_443_TCP_PROTO=tcp",
  "KUBERNETES_PORT_443_TCP_PORT=443",
  "KUBERNETES_PORT_443_TCP_ADDR=10.244.127.250",
  "KUBERNETES_RO_SERVICE_HOST=10.244.221.205",
  "KUBERNETES_RO_SERVICE_PORT=80",
  "KUBERNETES_RO_PORT=tcp://10.244.221.205:80",
  "KUBERNETES_RO_PORT_80_TCP=tcp://10.244.221.205:80",
  "KUBERNETES_RO_PORT_80_TCP_PROTO=tcp",
  "KUBERNETES_RO_PORT_80_TCP_PORT=80",
  "KUBERNETES_RO_PORT_80_TCP_ADDR=10.244.221.205",
  "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
  "HOME=/root"
]
```

Updating Pod.

```
$ kubectl update -f redis.yml 
redis-master

$ kubectl get po
POD                 IP                  CONTAINER(S)        IMAGE(S)            HOST                        LABELS              STATUS
redis-master        10.244.95.13        master              dockerfile/nginx    172.17.8.102/172.17.8.102   name=redis-master   Running

$ ssh node-01 "docker inspect a23a21e6cf44" | jq '.[].Config.Env'
[
  "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
  "HOME=/root"
]

```

**Comment by mbforbes** [comment]
Forgive me as I'm new to debugging these things: could you please post the `redis.yml` file that you used (before and after, if it changed) so I can repro?

**Comment by kazegusuri** [comment]
Before:
```
id: redis-master
kind: Pod
apiVersion: v1beta1
desiredState:
  manifest:
   version: v1beta1
   id: redis-master
   containers: 
     - 
       name: master
       image: dockerfile/redis
       cpu: 100
       ports: 
         - 
           containerPort: 6379
           hostPort: 6379
labels:
 name: redis-master
```

After:

```
id: redis-master
kind: Pod
apiVersion: v1beta1
desiredState:
  manifest:
   version: v1beta1
   id: redis-master
   containers: 
     - 
       name: master
       image: dockerfile/nginx # this line was changed
       cpu: 100
       ports: 
         - 
           containerPort: 6379
           hostPort: 6379
labels:
 name: redis-master
```
