### ISSUE TITLE
Pods hang in pending state indefinitely

### ISSUE THREAD

**Issue by heytrav** [GoogleCloudPlatform/kubernetes#4891]
When trying to start pods in my CoreOS cluster, they stay in a *Pending* state indefinitely and I cannot see any sign that the docker containers are being downloaded or anything else that would indicate that it is doing something to activate the controller. I am not sure if the problem is with my configuration but I thought I'd ask to see if someone else had encountered this problem.

Here is one of the controllers that I have been trying to run.
```yaml
id: elasticsearch-data
kind: ReplicationController
apiVersion: v1beta1
desiredState:
    replicas: 1
    replicaSelector:
        component: elasticsearch
        role: data
    podTemplate:
        desiredState:
            manifest:
                version: v1beta1
                id: elasticsearch-data
                containers:
                    - name: elasticsearch-data
                      image: quay.io/heytrav/elasticsearch:v0.0.8-data
                      ports:
                          - name: transport
                            containerPort: 9300
                      volumeMounts:
                          - name: es-persistent-storage
                            mountPath: "/data"
                            readOnly: false
                volumes:
                    - name: es-persistent-storage
                      source:
                          emptyDir: {}
        labels:
            component: elasticsearch
            role: data

```

I'm not really seeing much in the logs to indicate that there is something wrong, but the pod hangs in a *Pending* state:

```
core@bart ~/staging $ kubectl get pods
POD                        IP                  CONTAINER(S)         IMAGE(S)                                    HOST                LABELS                              STATUS
elasticsearch-data-gziey                       elasticsearch-data   quay.io/heytrav/elasticsearch:v0.0.8-data   10.132.218.185/     component=elasticsearch,role=data   Pending
```

I initially tried this on a 3 node cluster at Digital Ocean and now currently on just a single node. 

Here are the binaries that I'm running
```
core@bart ~ $ kube-controller-manager --version
Kubernetes v0.11.0-dirty
core@bart ~ $ kube-kubelet --version
-bash: kube-kubelet: command not found
core@bart ~ $ kubelet --version
Kubernetes v0.11.0-dirty
core@bart ~ $ kube-proxy --version
Kubernetes v0.11.0-dirty
core@bart ~ $ kube-scheduler --version
Kubernetes v0.11.0-dirty
core@bart ~ $ kube-api-server
-bash: kube-api-server: command not found
core@bart ~ $ kube-apiserver --version
Kubernetes v0.11.0-dirty
```

Any help debugging this would be appreciated
