### ISSUE TITLE
Kubectls sometimes fails to set-context causes cryptic e2e failures

### ISSUE THREAD

**Issue by bprashanth** [GoogleCloudPlatform/kubernetes#5100]
I did a make clean, followed by a ./hack/e2e-test.sh and found that even though my cluster seemed to be running (per `gcloud compute instance list` and ssh), the actual test suite didn't even start. `go run hack/e2e.go -isup` also returned false. From what I could tell from the logs, my e2e cluster was trying to contact 127.0.0.1 for validation. This immediately got me thinking about the .kubeconfig. 

I tried:
```
 ./cluster/kubectl.sh config set-context kubernetesdev_e2e-test-beeps
current-context: "local"
Running: ./cluster/../cluster/gce/../../_output/local/bin/linux/amd64/kubectl config set-context kubernetesdev_e2e-test-beeps
```

followed by:
```
 ./cluster/kubectl.sh config view
current-context: "local"
Running: ./cluster/../cluster/gce/../../_output/local/bin/linux/amd64/kubectl config view
clusters:
  kubernetesdev_e2e-test-beeps:
    certificate-authority: /usr/local/google/home/beeps/.kube/kubernetesdev_e2e-test-beeps/kubernetes.ca.crt
    server: https://104.197.12.100
  local:
    insecure-skip-tls-verify: true
    server: http://127.0.0.1:8080
contexts:
  gce:
    cluster: ""
    user: ""
  kubernetesdev_e2e-test-beeps:
    cluster: ""
    user: ""
  local:
    cluster: local
    user: ""
current-context: local
preferences: {}
users:
  kubernetesdev_e2e-test-beeps-admin:
    auth-path: /usr/local/google/home/beeps/.kube/kubernetesdev_e2e-test-beeps/kubernetes_auth
```
which confused me. So I dug around a bit and found the .kubeconfig file, which had:
```
apiVersion: v1                                                                                                                                                                                                                                                                          
clusters: []
contexts: []
current-context: kubernetesdev_e2e-test-beeps
kind: Config
preferences: {}
users: []
```

I then tried to correct things via something like:
```
cluster/kubectl.sh config set-cluster local --server=http://104.197.12.100 --certificate-authorit=/usr/local/google/home/beeps/.kube/kubernetesdev_e2e-test-beeps/kubernetes.ca.crt --global
  cluster/kubectl.sh config set-context kubernetesdev_e2e-test-beeps --cluster=kubernetesdev_e2e-test-beeps --global
  cluster/kubectl.sh config use-context kubernetesdev_e2e-test-beeps
```

But it didn't seem to help (by which i mean `./hack/e2e.go -isup` still failed). 
I might've hacked around a little more at this point, after which I just deleted my .kubeconfig. Surprisingly, it now worked. 
```
Running: ./cluster/../cluster/gce/../../_output/local/bin/linux/amd64/kubectl config view
clusters:
  kubernetesdev_e2e-test-beeps:
    certificate-authority: /usr/local/google/home/beeps/.kube/kubernetesdev_e2e-test-beeps/kubernetes.ca.crt
    server: https://104.197.12.100
  local:
    insecure-skip-tls-verify: true
    server: http://127.0.0.1:8080
contexts:
  kubernetesdev_e2e-test-beeps:
    cluster: kubernetesdev_e2e-test-beeps
    user: kubernetesdev_e2e-test-beeps-admin
  local:
    cluster: local
    user: ""
current-context: kubernetesdev_e2e-test-beeps
preferences: {}
users:
  kubernetesdev_e2e-test-beeps-admin:
    auth-path: /usr/local/google/home/beeps/.kube/kubernetesdev_e2e-test-beeps/kubernetes_auth
```

and `go run ./hack/e2e.go -isup` is happy. It would be nice if a `make clean` also just unset your context etc so I don't have to babysit my e2e runs. 

@jlowdermilk wdyt?

**Comment by bprashanth** [comment]
This is surely related to cross-cluster kubectl. 

```
$ ./cluster/kubectl.sh config view
current-context: "kubernetesdev_e2e-test-beeps-admin"
Running: ./cluster/../cluster/gce/../../_output/local/bin/linux/amd64/kubectl config view
clusters:
  kubernetesdev_e2e-test-beeps:
    certificate-authority: /usr/local/google/home/beeps/.kube/kubernetesdev_e2e-test-beeps/kubernetes.ca.crt
    server: https://104.197.12.100
  local:
    insecure-skip-tls-verify: true
    server: http://127.0.0.1:8080
contexts:
  kubernetesdev_e2e-test-beeps:
    cluster: kubernetesdev_e2e-test-beeps
    user: kubernetesdev_e2e-test-beeps-admin
  local:
    cluster: local
    user: ""
current-context: kubernetesdev_e2e-test-beeps-admin
preferences: {}
users:
  kubernetesdev_e2e-test-beeps-admin:
    auth-path: /usr/local/google/home/beeps/.kube/kubernetesdev_e2e-test-beeps/kubernetes_auth
```

-isup run output:
```
2015/03/05 16:19:14 Running: get status
Project: kubernetesdev
Zone: us-central1-b
current-context: "kubernetesdev_e2e-test-beeps-admin"
Running: /usr/local/google/home/beeps/goproj/src/github.com/GoogleCloudPlatform/kubernetes/hack/e2e-internal/../../cluster/../cluster/gce/../../_output/local/bin/linux/amd64/kubectl version
Client Version: version.Info{Major:"0", Minor:"12+", GitVersion:"v0.12.0-121-g404d5b1799ed85-dirty", GitCommit:"404d5b1799ed859d980120f78a4b3655dae213d7", GitTreeState:"dirty"}

(GET) http://localhost:8080/versionCouldn't read version from server: Get http://localhost:8080/version: dial tcp 127.0.0.1:8080: connection refused
2015/03/05 16:19:15 Error running get status: exit status 1
2015/03/05 16:19:15 Cluster is DOWN
```

Getting rid of .kubeconfig
```
beeps@linux3234:~/goproj/src/github.com/GoogleCloudPlatform/kubernetes$ mv ./.kubeconfig /tmp
beeps@linux3234:~/goproj/src/github.com/GoogleCloudPlatform/kubernetes$ ./cluster/kubectl.sh config view
current-context: "kubernetesdev_e2e-test-beeps"
Running: ./cluster/../cluster/gce/../../_output/local/bin/linux/amd64/kubectl config view
clusters:
  kubernetesdev_e2e-test-beeps:
    certificate-authority: /usr/local/google/home/beeps/.kube/kubernetesdev_e2e-test-beeps/kubernetes.ca.crt
    server: https://104.197.12.100
  local:
    insecure-skip-tls-verify: true
    server: http://127.0.0.1:8080
contexts:
  kubernetesdev_e2e-test-beeps:
    cluster: kubernetesdev_e2e-test-beeps
    user: kubernetesdev_e2e-test-beeps-admin
  local:
    cluster: local
    user: ""
current-context: kubernetesdev_e2e-test-beeps
preferences: {}
users:
  kubernetesdev_e2e-test-beeps-admin:
    auth-path: /usr/local/google/home/beeps/.kube/kubernetesdev_e2e-test-beeps/kubernetes_auth
```

isup output:
```
beeps@linux3234:~/goproj/src/github.com/GoogleCloudPlatform/kubernetes$ go run ./hack/e2e.go -isup -v
2015/03/05 16:19:49 Running: get status
Project: kubernetesdev
Zone: us-central1-b
current-context: "kubernetesdev_e2e-test-beeps"
Running: /usr/local/google/home/beeps/goproj/src/github.com/GoogleCloudPlatform/kubernetes/hack/e2e-internal/../../cluster/../cluster/gce/../../_output/local/bin/linux/amd64/kubectl version
Client Version: version.Info{Major:"0", Minor:"12+", GitVersion:"v0.12.0-121-g404d5b1799ed85-dirty", GitCommit:"404d5b1799ed859d980120f78a4b3655dae213d7", GitTreeState:"dirty"}

(GET) https://104.197.12.100/version
Couldn't read version from server: Get https://104.197.12.100/version: dial tcp 104.197.12.100:443: i/o timeout
```


Note that the first time isup did a GET on `localhost` and the second time it was on `104.197.12.100`, and the only difference between the runs was me mv'ing the .kubeconfig to /tmp.
