### ISSUE TITLE
Feature Request: honor publicIPs along with createExternalLoadBalancer

### ISSUE THREAD

**Issue by kylelemons** [GoogleCloudPlatform/kubernetes#6452]
This may be already covered by the `v1beta3` changes, #1161, or #1107, but I wanted to register my request in case it wasn't.

Caveat:  My exposure, at the moment, is purely via GKE:
```
Client Version: version.Info{Major:"0", Minor:"13+", GitVersion:"v0.13.1-1-ga68dc88831fc5d", GitCommit:"a68dc88831fc5da80a7dd5a79e0f4097b6a58920", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"13+", GitVersion:"v0.13.2-1-g58b98aca84becd", GitCommit:"58b98aca84becdabbfc8d719c47b375a6a1bc855", GitTreeState:"clean"}
```

I have a desire to maintain a single external IP address.  This seems simplest; I can use the same DNS name as I have in my SSL certificate for all of the services I'm running.  So, to that end, I requested a static IP address in GCE and have manually created the low-level loadbalancer for it and specified the static IP in my `publicIPs` list (without `createExternalLoadBalancer`) for the services I want externalized.  This works, but it required a lot of tinkering with firewalls and target pools and experimentation with the `createExternalLoadBalancer` flag before I figured out the right combination.  The first thing I tried was this:

```yaml
id: frontend
kind: Service
apiVersion: v1beta1
selector:
  app: frontend
labels:
  app: frontend
containerPort: 80
port: 80
createExternalLoadBalancer: true
publicIPs:
- 330.201.152.515
```

If it would be possible for that to be a valid input that would cause the GCE/GKE provider to create the right firewall, target pools, and load balancer (bonus points if it made one that was shared among all services with the same external IP), it might save some time for future intrepid explorers.
