### ISSUE TITLE
Secrets Creation Returning Incorrect Error

### ISSUE THREAD

**Issue by aronchick** [GoogleCloudPlatform/kubernetes#7511]
__Repro__:
1. Use the following .yml for a secret file bad-secret.yml
```yaml
kind: Secret
apiVersion: v1beta3
metadata:
  name: my-secrets
data:
  a_b: SldVQTFKNXZkS2c4cXFvNW6zOXVWZ3MydHNQclBhCg==
```

2. Run ```kubectl create -f bad-secret.yml```

__Expected__: Should have worked, or given character that was bad (underscore is apparently not valid)

__Actual__: See the following error:
```bash
$ kubectl create -f bad-secret.yml
ERROR: Error: secret "my-secrets" is invalid: data[a_b]: invalid value 'a_b': must match regex [A-Za-z_][A-Za-z0-9_]*
```
