### ISSUE TITLE
YAML manifest pod spec fails

### ISSUE THREAD

**Issue by satnam6502** [GoogleCloudPlatform/kubernetes#7594]
In the process of converting the manifest pod specs for node level logging from v1beta3 JSON to v1beta3 YAML I see int he Kubelet logs the error:
```
I0430 21:31:22.187256    4544 file.go:123] Can't process config file "/etc/kubernetes/manifests/fluentd-gcp.yaml": 
invalid pod: [spec.containers[0].pullPolicy: required value spec.restartPolicy: required value spec.dnsPolicy: requ
ired value]
```
However, the YAML file:
```
version: v1beta3
kind: Pod
metadata:
  name: fluentd-cloud-logging
spec:
  containers:
    - name: fluentd-cloud-logging
      image: gcr.io/google_containers/fluentd-gcp:1.5
      env:
        - name: FLUENTD_ARGS
          value: "-qq"
      volumeMounts:
        - name: containers
          mountPath: /var/lib/docker/containers
        - name: varlog
          mountPath: /varlog
  volumes:
    - name: containers
      hostPath:
        path: /var/lib/docker/containers
    - name: varlog
      hostPath:
        path: /var/log
```
has the same information as the JSON file:
```
{
 "apiVersion": "v1beta3",
 "kind": "Pod",
 "metadata": {"name": "fluentd-cloud-logging"},
 "spec": {
   "containers": [
     { "name": "fluentd-cloud-logging",
       "image": "gcr.io/google_containers/fluentd-gcp:1.5",
       "env": [
         { "name": "FLUENTD_ARGS",
           "value": "-qq"}
       ],
       "volumeMounts": [
         { "name": "varlog",
            "mountPath": "/varlog"},
         { "name": "containers",
           "mountPath": "/var/lib/docker/containers"}
       ]
     }
   ],
 "volumes": [
   { "name": "varlog",
     "hostPath": { "path": "/var/log"}
   },
   { "name": "containers",
     "hostPath": { "path": "/var/lib/docker/containers"}
   }
 ]
 }
}
```
but the JSON file works but the YAML file does not.

@wojtek-t
