### ISSUE TITLE
kubectl --validate flag doesn't complain about unknown fields

### ISSUE THREAD

**Issue by a-robinson** [GoogleCloudPlatform/kubernetes#7598]
My understanding of kubectl's --validate flag is that it's supposed to error out if it can't parse its input as a valid API object. Maybe my understanding is wrong, but if it isn't, then the --validate flag is currently broken.

This came up when a user's service was coming up without a load balancer when they used the following yaml:
```
kind: Service
apiVersion: v1beta3
metadata:
  name: locust-master
  labels:
    name: locust
    role: master
spec:
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
      name: locust-master-web
  selector:
    name: locust
    role: master
createExternalLoadBalancer: true
```

The createExternalLoadBalancer parameter is incorrectly at the top level, when it's supposed to be inside the spec. Running `kubectl create -f locust-master-service.yaml --validate` happily succeeds, with the server never seeing the createExternalLoadBalancer parameter.

You can make this even more extreme by throwing in arbitrarily named fields that don't exist anywhere in the API:
```
kind: Service
apiVersion: v1beta3
metadata:
  xxxxxxxxx: yyyyyyyy
  name: locust-master
  labels:
    name: locust
    role: master
spec:
  aaaaaaaa: bbbbbbbbb
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
      name: locust-master-web
  selector:
    name: locust
    role: master
```

Running `kubectl create -f locust-master-service.yaml --validate` with this input file also happily succeeds.

@brendandburns @jlowdermilk
