### ISSUE TITLE
Entrypoint not working in v1beta3

### ISSUE THREAD

**Issue by ddysher** [GoogleCloudPlatform/kubernetes#7608]
Create a rc with the following config won't work (v1beta3)
```yaml
kind: ReplicationController
apiVersion: v1beta3
metadata:
  name: kube-dns
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-dns
  template:
    metadata:
      labels:
        name: kube-dns
        k8s-app: kube-dns
        kubernetes.io/cluster-service: "true"
    spec:
      dnsPolicy: "Default"
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v2.0.3
          command:
            # "/etcd"
            - "-listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001"
            - "-initial-cluster-token=skydns-etcd"
            - "-advertise-client-urls=http://127.0.0.1:4001"
        - name: kube2sky
          image: gcr.io/google_containers/kube2sky:1.2
          command:
            # "/kube2sky"
            - "-domain=kubernetes.local"
        - name: skydns
          image: gcr.io/google_containers/skydns:2015-03-11-001
          command:
            # "/skydns"
            - "-machines=http://localhost:4001"
            - "-addr=0.0.0.0:53"
            - "-domain=kubernetes.local"
          ports:
            - name: dns
              containerPort: 53
              protocol: UDP
```
I have to comment out the binary command, i.e. /etcd, /skydns.  However, with v1beta1, it works:
```yaml
kind: ReplicationController
apiVersion: v1beta1
id: kube-dns
namespace: default
labels:
  k8s-app: kube-dns
  kubernetes.io/cluster-service: "true"
desiredState:
  replicas: 1
  replicaSelector:
    k8s-app: kube-dns
  podTemplate:
    labels:
      name: kube-dns
      k8s-app: kube-dns
      kubernetes.io/cluster-service: "true"
    desiredState:
      manifest:
        version: v1beta2
        id: kube-dns
        dnsPolicy: "Default"  # Don't use cluster DNS.
        containers:
          - name: etcd
            image: quay.io/coreos/etcd:v2.0.3
            command: [
                    "-listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001",
                    "-initial-cluster-token=skydns-etcd",
                    "-advertise-client-urls=http://127.0.0.1:4001",
            ]
          - name: kube2sky
            image: gcr.io/google_containers/kube2sky:1.2
            command: [
                    "-domain=kubernetes.local",
            ]
          - name: skydns
            image: gcr.io/google_containers/skydns:2015-03-11-001
            command: [
                    "-machines=http://localhost:4001",
                    "-addr=0.0.0.0:53",
                    "-domain=kubernetes.local",
            ]
            ports:
              - name: dns
                containerPort: 53
                protocol: UDP
```

For v1beta3, the error message is
```
Failed to start with docker id 8dd9b7e0066d35ce1879f1ad5db20d1465522633160774c845cdeb86467b3e0a with error: API error (500): Cannot start container 8dd9b7e0066d35ce1879f1ad5db20d1465522633160774c845cdeb86467b3e0a: [8] System error: exec: "-domain=kubernetes.local": executable file not found in $PATH
```
