### ISSUE TITLE
LivenessProbe of type exec appears completely broken

### ISSUE THREAD

**Issue by a-robinson** [GoogleCloudPlatform/kubernetes#7618]
As far as I can tell, container liveness probes of type exec flat out don't work against clusters built at head. I had the kubelet always log the output of the exec'ed command, and it's always empty no matter what I exec, causing the probe to fail since it requires the output to be equal to the string "ok".

If you want to test it, try adding a liveness probe of this form to any container:
```
livenessProbe:
  exec:
    command:
    - "/bin/sh"
    - "-c"
    - "echo ok"
```
I also tried these lovely forms, to more closely match the liveness example under examples/:
```
livenessProbe:
  exec:
    command:
    - "/bin/sh"
    - "-c"
    - "echo ok > temp; cat temp"
```
```
livenessProbe:
  exec:
    command:
    - "echo"
    - "ok"
```

On the plus side, this may be an opportunistic time to switch over to #7587
