### ISSUE TITLE
v1beta3 conversion using kube-version-change dropped attribute nodeSelector

### ISSUE THREAD

**Issue by mbforbes** [GoogleCloudPlatform/kubernetes#7800]
Reported via "Containers at Google" Google Group:

>I just tried out the kube-version-change, worked for me to convert from v1beta1 to v1beta3.  however, my database landed on the wrong node (minion), digging into i notice that the selector was dropped:
>```
>    nodeSelector: {databasenode: 'true'}
>```
>Here are my nodes:
>```
>    core@yb1 ~/prs $ kubectl get nodes
>    NAME            LABELS              STATUS
>    45.55.192.230   <none>              Ready
>    45.55.192.232   databasenode=true   Ready
>```
>I stuck the nodeSelector in the correct spot in the kube-version-change translated file and ran it again and the pod was created on the correct node.

**Comment by lavalamp** [comment]
I cannot reproduce on the below pod. I'll ask for the exact pre-conversion pod in the email thread.

```
apiVersion: v1beta1
desiredState:
  manifest:
    containers:
      - image: nginx
        name: nginx
    id: nginx
    version: v1beta1
id: nginx
kind: Pod
labels:
  env: test
nodeSelector:
  disktype: ssd
```
