### ISSUE TITLE
Secrets not surviving server reboot...

### ISSUE THREAD

**Issue by asautins** [GoogleCloudPlatform/kubernetes#7958]
I believe I'm seeing an issue where secrets are not available after server reboot. 

The steps to reproduce are below.  Note that the following steps have been run on v.0.16.2:

Create the following simple secret:

```
# From kubernetes/examples/secrets/secret.yaml
apiVersion: v1beta3
kind: Secret
metadata:
  name: test-secret
data:
  data-1: dmFsdWUtMQ0K
  data-2: dmFsdWUtMg0KDQo=
```

Then create the following pod:

```
apiVersion: v1beta3
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: test
    image: centos:centos7.0.1406
    command: [ "bash", "-c", "while [ true ]; do cat /etc/test-secret/data-1; sleep 5; done" ]
    volumeMounts:
    - mountPath: /etc/test-secret
      name: test-secret
      readOnly: true
  volumes:
  - name: test-secret
    secret:
      secretName: test-secret

```

After starting the pod you can see that it is correctly slowing the data-1 value from the secret

```
kubectl log test
2015-05-08T16:06:37.433196624Z value-1
```

Now reboot the server running the pod.  After reboot I see the following in the log output:

```
kubectl log test
2015-05-08T16:08:53.172253741Z cat: /etc/test-secret/data-1: No such file or directory
```

That seems to indicate to me that the pod is re-starting after the reboot but that it is unable to get the secret.  Note that after the reboot manually stopping ( kubectl stop pod test ) and re-starting the pod shows the expected results.

My expectation of the behavior is that if the server a pod is running on reboots that the pod will re-start with the same secret it had when it started previously.  If the secret had been updated since the pod had been originally started I would expect the original secret to be available.
