### ISSUE TITLE
Rolling update doesn't print useful messages when validation fails

### ISSUE THREAD

**Issue by brendandburns** [GoogleCloudPlatform/kubernetes#8167]
Thanks Jeff for the tip - I tried the rollingupdate with a v1beta3 controller and got "ERROR: Error: kubernetes/specs/controller-v6.yaml does not specify a valid ReplicationController". Here's my replicationcontroller in full:

```yaml
apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: socialscout
spec:
  selector:
    name: socialscout
    version: 6
  template:
    metadata:
      labels:
        name: socialscout
        version: 6
    spec:
      containers:
      - image: gcr.io/<proj_id>/socialscout:v6
        name: socialscout
        ports:
        - containerPort: 8080
          protocol: TCP
```
