### ISSUE TITLE
expected behavior of Container Exec health check

### ISSUE THREAD

**Issue by caesarxuchao** [GoogleCloudPlatform/kubernetes#8205]
In [kubernetes/examples/liveness/exec-liveness.yaml](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/liveness/exec-liveness.yaml), 
```
...
        livenessProbe:
          exec:
            command:
              - "cat"
              - "/tmp/health"
          initialDelaySeconds: 15
        command:
          - "/bin/sh"
          - "-c"
          - "echo ok > /tmp/health; sleep 10; echo fail > /tmp/health; sleep 600"
```
"kubeclt get pods" shows the failure via a termination message after the 600-second sleep. Is this the expected behavior? Or shall the failure be discovered once 'echo fail > /tmp/health' is executed? Thanks.
@brendandburns
