### ISSUE TITLE
Duplicate hostPorts Rejected Despite Disparate Protocols

### ISSUE THREAD

**Issue by eatnumber1** [GoogleCloudPlatform/kubernetes#8372]
Pods which use `hostPort` to bind both TCP and UDP sockets to the same port number are rejected with the error:

```
ERROR: Error: Pod "foo" is invalid: spec.containers[0].port: duplicate value '2049'
```

An example pod follows.

```yaml
apiVersion: v1beta3
kind: Pod
metadata:
  name: foo
spec:
  containers:
    - name: foo
      image: foo/bar
      ports:
        - name: foo-tcp
          containerPort: 2049
          protocol: tcp
          hostPort: 2049
        - name: foo-udp
          containerPort: 2049
          protocol: udp
          hostPort: 2049
```
