### ISSUE TITLE
Data-only container volume not populating

### ISSUE THREAD

**Issue by bkeroackdsc** [GoogleCloudPlatform/kubernetes#8426]
I have a pod with certain containers that export volumes and other containers that consume those volumes. Plain/manual Docker volumes works normally as expected, however when using k8s volumes within a pod/replicationcontroller the volume does not have all the data populated within the consuming container.

Example:

build-container (exports ``/opt``, which contains the following subdirectories: ``/opt/application``, ``/opt/dependencies``)
application-runner (mounts volume at /opt)

I used the following pod template excerpt within a RC:

```yaml
spec:
      containers:
        - name: application-runner
          image: myregistry.com:5000/application-runner:latest
          command: [ "/sbin/my_init" ]
          volumeMounts:
            - name: app-build
              mountPath: /opt
        - name: build-container
          image: myregistry.com:5000/build-container:latest
          command: [ "/sbin/my_init" ]
          volumeMounts:
            - name: app-build
              mountPath: /opt
      volumes:
        - name: app-build
          emptyDir: {}
```
The strange thing is that I can see the two subdirectories within the runner container:

```bash
core@ip-10-10-x-x ~ $ docker exec xxxxxxxxxx ls -lah /opt/
total 16K
drwxr-x--- 4 root root 4.0K May 18 18:26 .
drwxr-xr-x 1 root root 4.0K May 18 18:26 ..
drwxr-xr-x 3 app  root 4.0K May 18 18:26 application
drwxr-xr-x 9 app  root 4.0K May 18 18:26 dependencies
```

However they are empty:
```bash
core@ip-10-10-x-x ~ $ docker exec xxxxxxxxxxx ls -lah /opt/application/
total 8.0K
drwxr-xr-x 2 root root 4.0K May 18 18:26 .
drwxr-x--- 4 root root 4.0K May 18 18:26 ..
```

As stated previously, if I manually start the containers on the command line on the node, the runner container can see the data as expected:

```bash
$ docker run -d --name app-build myregistry.com:5000/build-container:latest /sbin/my_init
$ docker run -d --name app-runner --volumes-from=app-build myregistry.com:5000/application-runner:latest /sbin/my_init
```

Any ideas what's going on? This is k8s v0.15.0 on CoreOS within AWS.
