### ISSUE TITLE
Permissions problem when trying to mount multiple volumes

### ISSUE THREAD

**Issue by billnapier** [GoogleCloudPlatform/kubernetes#8554]
I've got 2 volumes defined in my pod (snippet)
         
```json
   "volumes":[
               {
                 "name": "bills-blog-data",
                   "gcePersistentDisk": {
                     "pdName": "bills-blog-data",
                     "fsType": "ext4",
                     "partition": 1
                 }
               },
               {
                 "name": "bills-blog-images",
                   "gcePersistentDisk": {
                     "pdName": "bills-blog-images",
                     "fsType": "ext4",
                     "partition": 1
                 }
               }
```

When I create these pods on GCE, the first one get's the proper permissions (in this case, napier:napier).  The second one always gets root:root.

```
ls -l /var/lib/kubelet/pods/16ba0669-febc-11e4-800f-42010af01f63/volumes/kubernetes.io~gce-pd/
total 8
drwxr-xr-x 3 napier napier 4096 May 20 06:08 bills-blog-data
drwxr-xr-x 3 root   root   4096 May 20 06:08 bills-blog-images
````

Of course, this causes issues when my blog software tries to read/write from the images partition.

**Comment by thockin** [comment]
Can you post a full pod spec.  When I run the below pod, it works fine:

```
apiVersion: v1beta3
kind: Pod
metadata:
  name: testvol
  namespace: default
spec:
  containers:
  - image: kubernetes/serve_hostname
    name: serve
    volumeMounts:
    - mountPath: /vol1
      name: vol1
      readOnly: true
    - mountPath: /vol2
      name: vol2
      readOnly: true
  volumes:
  - name: vol1
    gcePersistentDisk:
      pdName: testssd
      fsType: ext4
      readOnly: true
  - name: vol2
    gcePersistentDisk:
      pdName: testdisk
      fsType: ext4
      readOnly: true

```
