### ISSUE TITLE
Support YAML files in config directory for Kubelet

### ISSUE THREAD

**Issue by jseaidou** [GoogleCloudPlatform/kubernetes#8692]
When validating the Pod object in the config file source from the config directory by the kubelet, it only supports JSON. For parity with Pod configs used with the API Server, the validation should also support YAML

**Comment by yujuhong** [comment]
@jseaidou, I believe kubelet does accept YAML files. 
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/config/common.go#L94

Does this not work for you? What version are you running?

**Comment by jseaidou** [comment]
@yujuhong It does not. I am running 0.16 release. 
This is the JSON version that works
```
{
    "APIVersion": "v1beta3",
    "Kind": "Pod",
    "Spec": {
        "Containers": [
            {
                "Name": "pod name",
                "Image": "path to image",
                "Ports": [{
                    "ContainerPort": 9000,
                    "HostPort": 9107
                }],
                "Env": [
                    {
                        "name": "VERSION",
                        "value": "v1"
                    }
                ],
                "VolumeMounts": [
                    {
                        "Name": "certs",
                        "mountPath": "/box/etc/pki",
                        "readOnly": true
                    },
                    {
                        "Name": "logs",
                        "mountPath": "/box/var/log",
                        "readOnly": false
                    }
                ]
            }
        ],
        "Volumes": [
            {
                "Name": "certs",
                "HostPath": {
                    "Path": "/box/etc/pki"
                }
            },
            {
                "Name": "logs",
                "HostPath": {
                    "Path": "/box/var/log"
                }
            }
        ]
    }
}
```

and the matching YAML that fails and says the following 
    
    couldn't parse as neither manifest (invalid manifest: [version: required value containers: required value]) nor pod (couldn't get version/kind: invalid character 'i' looking for beginning of value).

```
PIVersion: v1beta3
Kind: Pod
Spec:
  Containers:
    - Name: pod-name
      Image: path-to-registry
      Ports:
        - containerPort: 9000
          hostPort: 9107
      Env:
        - name: VERSION
          value: v1
      VolumeMounts:
        - name: certs
          mountPath: /box/etc/pki
          readOnly: true
        - name: logs
          mountPath: /box/var/log/
          readOnly: false
      ReadinessProbe:
        HTTPGet:
          Path: ready-to-serve
          Port: 9000
        InitialDelaySeconds: 10
  Volumes:
    - name: certs
      HostPath:
        Path: /box/etc/pki
    - name: logs
      HostPath:
        Path: /box/var/log
```
