### ISSUE TITLE
Problems specifying memory limits in Pods

### ISSUE THREAD

**Issue by micafer** [GoogleCloudPlatform/kubernetes#8814]
I'm trying to create a Pod using a very simple example. In fact is the pod.yaml example only adding a memory limit:

```
apiVersion: v1beta3
kind: Pod
metadata:
  labels:
    name: nginx
  name: nginx
  namespace: default
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
       limits:
         memory: 536870912
  restartPolicy: Always
```
The Pod is created also the corresponding docker container.

But the Pod remains in state "Pending" and it shows this message:
```
Query container info failed with error (json: cannot unmarshal number 5.36870912e+08 into Go value of type int64)
```

It seems that it has some problems getting the amount of memory of the container provided by docker.
If I inspect the created container, the amount of memory provider by docker is 
```
"Memory": 5.36870912e+08
```

If fact I try to delete the Pod and the associated container is not deleted.

I'm using the last kubernetes version downloaded from the Github repo using the v1beta3 API version.
I launch kubernetes using the local-up-cluster.sh script.
I'm using Go version 1.4.2 on an Ubuntu 14.04.2.
