### ISSUE TITLE
kubectl: bad error message for version-less yaml

### ISSUE THREAD

**Issue by thockin** [GoogleCloudPlatform/kubernetes#9011]
Given yaml without an apiversion:

```
$ k create -f /tmp/y
Error from server: The POST operation against Pod could not be completed at this time, please try again.
```

not very helpful

**Comment by mikedanese** [comment]
I am actually able to create a pod without and apiVersion.
```
➜  kubernetes git:(kubectl-kind-err) ✗ cat bonkers/no-version.yml 
kind: Pod
metadata:
  labels:
    name: redis
    redis-sentinel: "true"
    role: master
  name: redis-master
spec:
  containers:
    - name: master
      image: kubernetes/redis:v1
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: "1"
      volumeMounts:
        - mountPath: /redis-master-data
          name: data
    - name: sentinel
      image: kubernetes/redis:v1
      env:
        - name: SENTINEL
          value: "true"
      ports:
        - containerPort: 26379
  volumes:
    - name: data
      emptyDir: {}      
➜  kubernetes git:(kubectl-kind-err) ✗ ./_output/local/bin/linux/amd64/kubectl create -f bonkers/no-version.yml --v=2
hack/build-go.sh cmd/kubectl
pods/redis-master
```
Maybe there was something else going on.

I assume it's using the --api-version? @jlowdermilk is this the expected behavior?
