### ISSUE TITLE
Service update should preserve clusterIP if not specified

### ISSUE THREAD

**Issue by matthiasr** [GoogleCloudPlatform/kubernetes#9374]
Trying to update a service that does not specify a clusterIP, I hit [this](https://github.com/GoogleCloudPlatform/kubernetes/blob/0f1c4c25c344f70c3592040b2ef092ccdce0244f/pkg/api/validation/validation.go#L1160-L1162) condition with the error message

```
$ kubectl update -f workstation/workstation-service.yaml
service "workstation" is invalid: spec.clusterIP: invalid value '': field is immutable
```

As far as I can tell, what happens is that the YAML deserialization communicates absence via the Go zero value, and the validation thinks I'm trying to set the clusterIP to an empty string.

I think correct behaviour in this case would be to just keep the old value.

For completeness, the service definition in question is

```yaml
apiVersion: v1beta3
kind: Service
metadata:
  name: workstation
spec:
  selector:
    app: workstation
  ports:
  - name: ssh
    port: 22
    protocol: TCP
```

and the only change I made was to the selector labels.
