### ISSUE TITLE
Kube-dns - kube2sky fails with  /etc/dns_token/kubeconfig: no such file or directory

### ISSUE THREAD

**Issue by akamalov** [GoogleCloudPlatform/kubernetes#9857]
<b> Environment </b>

```CoreOS: 695```
```Kubernetes release: 0.18.0```

Following examples described at https://github.com/GoogleCloudPlatform/kubernetes/tree/afedb2d24a920dc3de4f10926c1f93accf0d93ed/cluster/addons/dns to setup Kube-DNS. However, I am getting an error trying to run kube-dns:

```
I0616 12:21:06.247816       1 kube2sky.go:388] Etcd server found: http://127.0.0.1:4001
F0616 12:21:07.249143       1 kube2sky.go:513] Failed to create a kubernetes client: stat /etc/dns_token/kubeconfig: no such file or directory
```

Here is my service file: ```kube-dns.service```
```
apiVersion: v1beta3
kind: Service
metadata:
  name: kube-dns
  namespace: default
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeDNS"
spec:
  selector:
    k8s-app: kube-dns
  portalIP: 10.100.0.10 
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
```

Here is my ```rc``` file: ```kube-dns.controller```

```
apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: kube-dns-v3
  namespace: default
  labels:
    k8s-app: kube-dns-v3
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1 
  selector:
    k8s-app: kube-dns
    version: v3
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v3
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: etcd
        image: gcr.io/google_containers/etcd:2.0.9
        command:
        - /usr/local/bin/etcd
        - -listen-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -advertise-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -initial-cluster-token
        - skydns-etcd
      - name: kube2sky
        image: gcr.io/google_containers/kube2sky:1.9
        args:
        # command = "/kube2sky"
        - -domain=kubdomain.local
        - -kubecfg_file=/etc/dns_token/kubeconfig
        volumeMounts:
        - mountPath: /etc/dns_token
          name: dns-token
          readOnly: true
      - name: skydns
        image: gcr.io/google_containers/skydns:2015-03-11-001
        args:
        # command = "/skydns"
        - -machines=http://localhost:4001
        - -addr=0.0.0.0:53
        - -domain=kubedomain.local
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - nslookup kubernetes.default.kubedomain.local localhost >/dev/null
          initialDelaySeconds: 30
          timeoutSeconds: 5
      dnsPolicy: Default  # Don't use cluster DNS.
      volumes:
      - name: dns-token
        secret:
          secretName: token-system-dns
```
Secrets file: ```token-system-dns.json ```

```
{
  "apiVersion": "v1beta2",
  "kind": "Secret",
  "id": "token-system-dns",
  "data": {
  }
}
```

Created secrets file:

```
wwserver60 ~ #  kubectl create -f token-system-dns.json --namespace=default
secrets/token-system-dns
```

When launched, my kube2sky fails with:

```
I0616 12:21:06.247816       1 kube2sky.go:388] Etcd server found: http://127.0.0.1:4001
F0616 12:21:07.249143       1 kube2sky.go:513] Failed to create a kubernetes client: stat /etc/dns_token/kubeconfig: no such file or directory
```

Any clues where should I be looking at ?

Thanks a ton!!

**Comment by bakins** [comment]
Try changing your secrete to be something like:

```json
{
    "apiVersion": "v1",
    "kind": "Secret",
    "metadata": {
        "name": "token-system-dns",
        "namespace": "default"
    },
    "data": {
        "kubeconfig": "Cg=="
    }
}
```

This will create an empty file for kubeconfig.

**Comment by akamalov** [comment]
Hey Brian Thank You so much for the help. It worked with the following config:

```
{
  "apiVersion": "v1beta2",
  "kind": "Secret",
  "id": "token-system-dns",
  "namespace": "default",
  "data": {
      "kubeconfig": "Cg=="
  }
}
```
Again, thanks so much!

Alex

**Comment by akamalov** [comment]
Changed the secret setting to slightly different to get it up and running:

File: ``` token-system-dns.json```

```
# cat token-system-dns.json 
{
    "apiVersion": "v1",
    "kind": "Secret",
    "metadata": {
        "name": "token-system-dns",
        "namespace": "default"
    },
    "data": {
        "kubeconfig": "Cg=="
    }
}
```

My API server is listening on port ```:8888``` instead of ```:8080``` due to Marathon already running on port ```8080```. Thus, I moved the port to ```:8888```. Now, I am getting errors trying to get ```skydns``` working:

From a master node:

```
# kubectl get pods --namespace=default
POD                 IP           CONTAINER(S)   IMAGE(S)                                         HOST                      LABELS                                                           STATUS    CREATED      MESSAGE
kube-dns-v3-d6wov   11.16.0.12                                                                   10.9.158.77/10.9.158.77   k8s-app=kube-dns,kubernetes.io/cluster-service=true,version=v3   Running   20 hours     
                                 kube2sky       gcr.io/google_containers/kube2sky:1.9                                                                                                       Running   20 hours     
                                 etcd           gcr.io/google_containers/etcd:2.0.9                                                                                                         Running   20 hours     
                                 skydns         gcr.io/google_containers/skydns:2015-03-11-001                                                                                              Running   35 seconds   last termination: exit code 2
```

As yo can see ```skydns``` exited with an error code <b>2</b>

From a worker node:

```
# docker ps -a
CONTAINER ID        IMAGE                                            COMMAND                CREATED              STATUS                          PORTS                                                                                                                                                NAMES
6e0a18134377        gcr.io/google_containers/skydns:2015-03-11-001   "/skydns -machines=h   18 seconds ago       Up 16 seconds                                                                                                                                                                        k8s_skydns.506dd339_kube-dns-v3-d6wov_default_21ab1e8d-143c-11e5-9570-005056881b7e_7184cc44     
bd8a46598595        gcr.io/google_containers/skydns:2015-03-11-001   "/skydns -machines=h   48 seconds ago       Exited (2) 17 seconds ago                                                                                                                                                            k8s_skydns.506dd339_kube-dns-v3-d6wov_default_21ab1e8d-143c-11e5-9570-005056881b7e_9fb90a9d     
97949303be42        gcr.io/google_containers/skydns:2015-03-11-001   "/skydns -machines=h   About a minute ago   Exited (2) 47 seconds ago                                                                                                                                                            k8s_skydns.506dd339_kube-dns-v3-d6wov_default_21ab1e8d-143c-11e5-9570-005056881b7e_120fc94b     
ed73e6d4d19e        gcr.io/google_containers/skydns:2015-03-11-001   "/skydns -machines=h   2 minutes ago        Exited (2) About a minute ago                                                                                                                                                        k8s_skydns.506dd339_kube-dns-v3-d6wov_default_21ab1e8d-143c-11e5-9570-005056881b7e_f04d347e     
24d38bff9157        gcr.io/google_containers/skydns:2015-03-11-001   "/skydns -machines=h   2 minutes ago        Exited (2) 2 minutes ago                                                                                                                                                             k8s_skydns.506dd339_kube-dns-v3-d6wov_default_21ab1e8d-143c-11e5-9570-005056881b7e_38d8bdd6     
1cfcec6da4a5        gcr.io/google_containers/kube2sky:1.9            "/kube2sky -domain=k   20 hours ago         Up 20 hours                                                                                                                                                                          k8s_kube2sky.64194896_kube-dns-v3-d6wov_default_21ab1e8d-143c-11e5-9570-005056881b7e_2c4a0856   
c346eadba4de        gcr.io/google_containers/etcd:2.0.9              "/usr/local/bin/etcd   20 hours ago         Up 20 hours                                                                                                                                                                          k8s_etcd.748a4ba3_kube-dns-v3-d6wov_default_21ab1e8d-143c-11e5-9570-005056881b7e_fead5fe9       
9ece27c683f4        gcr.io/google_containers/pause:0.8.0             "/pause"               20 hours ago         Up 20 hours                                                                                                                                                                          k8s_POD.8fdb0e41_kube-dns-v3-d6wov_default_21ab1e8d-143c-11e5-9570-005056881b7e_cadb745a        
```

SkyDNS container logs:

```
# docker logs bd8a46598595
2015/06/17 11:35:10 skydns: falling back to default configuration, could not read from etcd: 100: Key not found (/skydns) [2]
2015/06/17 11:35:10 skydns: ready for queries on kubedomain.local. for tcp://0.0.0.0:53 [rcache 0]
2015/06/17 11:35:10 skydns: ready for queries on kubedomain.local. for udp://0.0.0.0:53 [rcache 0]
```
Kube2Sky container logs:

```
E0616 20:41:54.281963       1 reflector.go:136] Failed to list *api.Endpoints: Get http://localhost:8080/api/v1beta3/endpoints: dial tcp 127.0.0.1:8080: connection refused
E0616 20:41:54.302504       1 reflector.go:136] Failed to list *api.Service: Get http://localhost:8080/api/v1beta3/services: dial tcp 127.0.0.1:8080: connection refused
E0616 20:41:55.283067       1 reflector.go:136] Failed to list *api.Endpoints: Get http://localhost:8080/api/v1beta3/endpoints: dial tcp 127.0.0.1:8080: connection refused
E0616 20:41:55.303444       1 reflector.go:136] Failed to list *api.Service: Get http://localhost:8080/api/v1beta3/services: dial tcp 127.0.0.1:8080: connection refused
E0616 20:41:56.284272       1 reflector.go:136] Failed to list *api.Endpoints: Get http://localhost:8080/api/v1beta3/endpoints: dial tcp 127.0.0.1:8080: connection refused
E0616 20:41:56.304159       1 reflector.go:136] Failed to list *api.Service: Get http://localhost:8080/api/v1beta3/services: dial tcp 127.0.0.1:8080: connection refused
E0616 20:41:57.285927       1 reflector.go:136] Failed to list *api.Endpoints: Get http://localhost:8080/api/v1beta3/endpoints: dial tcp 127.0.0.1:8080: connection refused
```

So, for some reason, ```kube2sky``` is dialing to localhost and port ```:8080```.  I am assuming here it is trying to reach k8 API server. Question is, if it is trying to reach API server, how should I be providing a parameter in service file to point to a master node and to a correct port ?

Thanks a metric ton!!

**Comment by bakins** [comment]
@akamalov maybe try editing the [rc manifest](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/addons/dns/skydns-rc.yaml.in) for kube2sky to add `--kube-master-url=<your-master-url>` ?  You may even be able to use variable substitution there.

**Comment by akamalov** [comment]
Thanks SO MUCH, Brian. Yep, I got ```kube2sky``` working properly. Here is my yaml file:

```
apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: kube-dns-v3
  namespace: default
  labels:
    k8s-app: kube-dns-v3
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1 
  selector:
    k8s-app: kube-dns
    version: v3
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v3
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: etcd
        image: gcr.io/google_containers/etcd:2.0.9
        command:
        - /usr/local/bin/etcd
        - -listen-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -advertise-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -initial-cluster-token
        - skydns-etcd
      - name: kube2sky
        image: gcr.io/google_containers/kube2sky:1.9
        args:
        # command = "/kube2sky"
        - -domain=kubdomain.local
        - -kubecfg_file=/etc/dns_token/kubeconfig
        - -kube_master_url=http://10.9.158.219:8888
        volumeMounts:
        - mountPath: /etc/dns_token
          name: dns-token
          readOnly: true
      - name: skydns
        image: gcr.io/google_containers/skydns:2015-03-11-001
        args:
        # command = "/skydns"
        - -machines=http://localhost:4001
        - -addr=0.0.0.0:53
        - -domain=kubedomain.local
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - nslookup kubernetes.default.kubedomain.local localhost >/dev/null
          initialDelaySeconds: 30
          timeoutSeconds: 5
      dnsPolicy: Default  # Don't use cluster DNS.
      volumes:
      - name: dns-token
        secret:
          secretName: token-system-dns
```
However, I am continuously getting errors on ```skydns```: complaining that ETCD does not have the proper ```/skydns``` key:

```
wwserver206 coreos-install # docker logs 8ea8c7528264 
2015/06/18 16:33:05 skydns: falling back to default configuration, could not read from etcd: 100: Key not found (/skydns/config) [10]
2015/06/18 16:33:05 skydns: ready for queries on kubedomain.local. for tcp://0.0.0.0:53 [rcache 0]
2015/06/18 16:33:05 skydns: ready for queries on kubedomain.local. for udp://0.0.0.0:53 [rcache 0]
wwserver206 coreos-install # 
```

So, it looks like ETCD key "/skydns/config" is missing. Shouldn't this be part of the manifest ?

Thanks so much again!

Alex

**Comment by bakins** [comment]
@akamalov You can store the skydns config in etcd, but it is not required.  You can safely ignore that error.

**Comment by akamalov** [comment]
Thanks Brian!!! Let me try it out!!

**Comment by akamalov** [comment]
Hey Brian, 

At this point, my skydns instance is not staying up:

```
wwserver206 coreos-install # docker ps -a
CONTAINER ID        IMAGE                                            COMMAND                CREATED              STATUS                          PORTS               NAMES
5adf9a16dac6        gcr.io/google_containers/skydns:2015-03-11-001   "/skydns -machines=h   13 seconds ago       Up 11 seconds                                       k8s_skydns.c3bf943b_kube-dns-v3-faec0_default_7f158857-1605-11e5-9219-005056881b7e_8bfe59c0     
20bb165bf25b        gcr.io/google_containers/skydns:2015-03-11-001   "/skydns -machines=h   44 seconds ago       Exited (2) 13 seconds ago                           k8s_skydns.c3bf943b_kube-dns-v3-faec0_default_7f158857-1605-11e5-9219-005056881b7e_f8616d6e     
0b7e7f4c1917        gcr.io/google_containers/skydns:2015-03-11-001   "/skydns -machines=h   About a minute ago   Exited (2) 43 seconds ago                           k8s_skydns.c3bf943b_kube-dns-v3-faec0_default_7f158857-1605-11e5-9219-005056881b7e_cb1cecb7     
939aea4f6129        gcr.io/google_containers/skydns:2015-03-11-001   "/skydns -machines=h   About a minute ago   Exited (2) About a minute ago                       k8s_skydns.c3bf943b_kube-dns-v3-faec0_default_7f158857-1605-11e5-9219-005056881b7e_6302cbb5     
3a9e44b18a58        gcr.io/google_containers/kube2sky:1.9            "/kube2sky -domain=k   About a minute ago   Up About a minute                                   k8s_kube2sky.b24d1636_kube-dns-v3-faec0_default_7f158857-1605-11e5-9219-005056881b7e_06096312   
b9540e0ac8bc        gcr.io/google_containers/etcd:2.0.9              "/usr/local/bin/etcd   About a minute ago   Up About a minute                                   k8s_etcd.ac140ca5_kube-dns-v3-faec0_default_7f158857-1605-11e5-9219-005056881b7e_0c7ce9de       
7fa6455fad3e        gcr.io/google_containers/pause:0.8.0             "/pause"               About a minute ago   Up About a minute                                   k8s_POD.8fdb0e41_kube-dns-v3-faec0_default_7f158857-1605-11e5-9219-005056881b7e_f176a03e        
0b7966a80b74        weaveworks/scope:0.3.0                           "/home/weave/entrypo   9 hours ago          Up 9 hours                                          weavescope                                                                                      
41114e8cb174        progrium/registrator:latest                      "/bin/registrator co   9 hours ago          Up 9 hours                                          registrator                                                                                     
wwserver206 coreos-install #   
```

The only error I am getting on docker logs is the container complaining at key not being found:

```
wwserver206 coreos-install # docker logs 939aea4f6129
2015/06/18 22:01:01 skydns: falling back to default configuration, could not read from etcd: 100: Key not found (/skydns) [1]
2015/06/18 22:01:01 skydns: ready for queries on kubedomain.local. for tcp://0.0.0.0:53 [rcache 0]
2015/06/18 22:01:01 skydns: ready for queries on kubedomain.local. for udp://0.0.0.0:53 [rcache 0]
wwserver206 coreos-install # 
```

From a master node:

```
wwserver60 ~ # kubectl describe pods $(kubectl get pods --namespace=default |grep kube-dns |awk '{ print $1}') --namespace=default
W0618 22:05:00.436127   26791 request.go:302] field selector: v1 - events - involvedObject.namespace - default: need to check if this is versioned correctly.
W0618 22:05:00.436339   26791 request.go:302] field selector: v1 - events - involvedObject.uid - 7f158857-1605-11e5-9219-005056881b7e: need to check if this is versioned correctly.
W0618 22:05:00.436420   26791 request.go:302] field selector: v1 - events - involvedObject.name - kube-dns-v3-faec0: need to check if this is versioned correctly.
Name:                           kube-dns-v3-faec0
Image(s):                       gcr.io/google_containers/etcd:2.0.9,gcr.io/google_containers/kube2sky:1.9,gcr.io/google_containers/skydns:2015-03-11-001
Node:                           10.9.159.77/10.9.159.77
Labels:                         k8s-app=kube-dns,kubernetes.io/cluster-service=true,version=v3
Status:                         Running
Replication Controllers:        kube-dns-v3 (1/1 replicas created)
Containers:
  etcd:
    Image:              gcr.io/google_containers/etcd:2.0.9
    State:              Running
      Started:          Thu, 18 Jun 2015 22:00:59 +0000
    Ready:              True
    Restart Count:      0
  skydns:
    Image:              gcr.io/google_containers/skydns:2015-03-11-001
    State:              Running
      Started:          Thu, 18 Jun 2015 22:04:58 +0000
    Ready:              False
    Restart Count:      4
  kube2sky:
    Image:              gcr.io/google_containers/kube2sky:1.9
    State:              Running
      Started:          Thu, 18 Jun 2015 22:01:01 +0000
    Ready:              True
    Restart Count:      0
Conditions:
  Type          Status
  Ready         False 
Events:
  FirstSeen                             LastSeen                        Count   From                    SubobjectPath                           Reason          Message
  Thu, 18 Jun 2015 22:00:57 +0000       Thu, 18 Jun 2015 22:00:57 +0000 1       {kubelet 10.9.159.77}   implicitly required container POD       pulled          Successfully pulled image "gcr.io/google_containers/pause:0.8.0"
  Thu, 18 Jun 2015 22:00:57 +0000       Thu, 18 Jun 2015 22:00:57 +0000 1       {scheduler }                                                    scheduled       Successfully assigned kube-dns-v3-faec0 to 10.9.159.77
  Thu, 18 Jun 2015 22:00:59 +0000       Thu, 18 Jun 2015 22:00:59 +0000 1       {kubelet 10.9.159.77}   implicitly required container POD       started         Started with docker id 7fa6455fad3e49b0c8f3daf5ea2ceaee78e55739c0c67461cf5cb911a4caa200
  Thu, 18 Jun 2015 22:00:59 +0000       Thu, 18 Jun 2015 22:00:59 +0000 1       {kubelet 10.9.159.77}   spec.containers{etcd}                   created         Created with docker id b9540e0ac8bc4e9d19b64f115b273c0e6ae5a4899b906448eb4036adbc07f279
  Thu, 18 Jun 2015 22:00:59 +0000       Thu, 18 Jun 2015 22:00:59 +0000 1       {kubelet 10.9.159.77}   spec.containers{etcd}                   started         Started with docker id b9540e0ac8bc4e9d19b64f115b273c0e6ae5a4899b906448eb4036adbc07f279
  Thu, 18 Jun 2015 22:00:59 +0000       Thu, 18 Jun 2015 22:00:59 +0000 1       {kubelet 10.9.159.77}   implicitly required container POD       created         Created with docker id 7fa6455fad3e49b0c8f3daf5ea2ceaee78e55739c0c67461cf5cb911a4caa200
  Thu, 18 Jun 2015 22:01:01 +0000       Thu, 18 Jun 2015 22:01:01 +0000 1       {kubelet 10.9.159.77}   spec.containers{kube2sky}               created         Created with docker id 3a9e44b18a58f76a4ba6ba8b6efee4482a59a3517c2ca06e139af7d996cedbde
  Thu, 18 Jun 2015 22:01:01 +0000       Thu, 18 Jun 2015 22:01:01 +0000 1       {kubelet 10.9.159.77}   spec.containers{kube2sky}               started         Started with docker id 3a9e44b18a58f76a4ba6ba8b6efee4482a59a3517c2ca06e139af7d996cedbde
  Thu, 18 Jun 2015 22:01:01 +0000       Thu, 18 Jun 2015 22:01:01 +0000 1       {kubelet 10.9.159.77}   spec.containers{skydns}                 created         Created with docker id 939aea4f61292b12197057015076cfee94d84c445a41e44a8188a937c83eeefd
  Thu, 18 Jun 2015 22:01:01 +0000       Thu, 18 Jun 2015 22:01:01 +0000 1       {kubelet 10.9.159.77}   spec.containers{skydns}                 started         Started with docker id 939aea4f61292b12197057015076cfee94d84c445a41e44a8188a937c83eeefd
  Thu, 18 Jun 2015 22:01:37 +0000       Thu, 18 Jun 2015 22:01:37 +0000 1       {kubelet 10.9.159.77}   spec.containers{skydns}                 killing         Killing 939aea4f61292b12197057015076cfee94d84c445a41e44a8188a937c83eeefd
  Thu, 18 Jun 2015 22:01:38 +0000       Thu, 18 Jun 2015 22:01:38 +0000 1       {kubelet 10.9.159.77}   spec.containers{skydns}                 started         Started with docker id 0b7e7f4c1917390fa0e476e8932cdfe6149b473b753d7d7343df282c12f90385
  Thu, 18 Jun 2015 22:01:38 +0000       Thu, 18 Jun 2015 22:01:38 +0000 1       {kubelet 10.9.159.77}   spec.containers{skydns}                 created         Created with docker id 0b7e7f4c1917390fa0e476e8932cdfe6149b473b753d7d7343df282c12f90385
  Thu, 18 Jun 2015 22:02:07 +0000       Thu, 18 Jun 2015 22:02:07 +0000 1       {kubelet 10.9.159.77}   spec.containers{skydns}                 killing         Killing 0b7e7f4c1917390fa0e476e8932cdfe6149b473b753d7d7343df282c12f90385
  Thu, 18 Jun 2015 22:02:08 +0000       Thu, 18 Jun 2015 22:02:08 +0000 1       {kubelet 10.9.159.77}   spec.containers{skydns}                 created         Created with docker id 20bb165bf25b5db6ee39dc38e964f25e56a7859cd96a38a4cd151173bf1e00f6
  Thu, 18 Jun 2015 22:02:09 +0000       Thu, 18 Jun 2015 22:02:09 +0000 1       {kubelet 10.9.159.77}   spec.containers{skydns}                 started         Started with docker id 20bb165bf25b5db6ee39dc38e964f25e56a7859cd96a38a4cd151173bf1e00f6
  Thu, 18 Jun 2015 22:02:38 +0000       Thu, 18 Jun 2015 22:02:38 +0000 1       {kubelet 10.9.159.77}   spec.containers{skydns}                 killing         Killing 20bb165bf25b5db6ee39dc38e964f25e56a7859cd96a38a4cd151173bf1e00f6
  Thu, 18 Jun 2015 22:02:39 +0000       Thu, 18 Jun 2015 22:02:39 +0000 1       {kubelet 10.9.159.77}   spec.containers{skydns}                 created         Created with docker id 5adf9a16dac64c85fa51c1c6b50b206f8d31417a71f42af96f2725b8fd13183b
  Thu, 18 Jun 2015 22:02:40 +0000       Thu, 18 Jun 2015 22:02:40 +0000 1       {kubelet 10.9.159.77}   spec.containers{skydns}                 started         Started with docker id 5adf9a16dac64c85fa51c1c6b50b206f8d31417a71f42af96f2725b8fd13183b
  Thu, 18 Jun 2015 22:03:18 +0000       Thu, 18 Jun 2015 22:03:18 +0000 1       {kubelet 10.9.159.77}   spec.containers{skydns}                 killing         Killing 5adf9a16dac64c85fa51c1c6b50b206f8d31417a71f42af96f2725b8fd13183b
  Thu, 18 Jun 2015 22:03:19 +0000       Thu, 18 Jun 2015 22:03:19 +0000 1       {kubelet 10.9.159.77}   spec.containers{skydns}                 created         Created with docker id d995d415dd413d23c06b773a370c4201c8fd94740a73ca003e0568a83b243db0
  Thu, 18 Jun 2015 22:03:19 +0000       Thu, 18 Jun 2015 22:03:19 +0000 1       {kubelet 10.9.159.77}   spec.containers{skydns}                 started         Started with docker id d995d415dd413d23c06b773a370c4201c8fd94740a73ca003e0568a83b243db0
  Thu, 18 Jun 2015 22:03:57 +0000       Thu, 18 Jun 2015 22:03:57 +0000 1       {kubelet 10.9.159.77}   spec.containers{skydns}                 killing         Killing d995d415dd413d23c06b773a370c4201c8fd94740a73ca003e0568a83b243db0
  Thu, 18 Jun 2015 22:03:58 +0000       Thu, 18 Jun 2015 22:03:58 +0000 1       {kubelet 10.9.159.77}   spec.containers{skydns}                 started         Started with docker id c751e6c7c8863cfc6673dd69a49f702fc4b3a66bcd7260f82e6ace66aba481a7
  Thu, 18 Jun 2015 22:03:58 +0000       Thu, 18 Jun 2015 22:03:58 +0000 1       {kubelet 10.9.159.77}   spec.containers{skydns}                 created         Created with docker id c751e6c7c8863cfc6673dd69a49f702fc4b3a66bcd7260f82e6ace66aba481a7
  Thu, 18 Jun 2015 22:04:27 +0000       Thu, 18 Jun 2015 22:04:27 +0000 1       {kubelet 10.9.159.77}   spec.containers{skydns}                 killing         Killing c751e6c7c8863cfc6673dd69a49f702fc4b3a66bcd7260f82e6ace66aba481a7
  Thu, 18 Jun 2015 22:04:29 +0000       Thu, 18 Jun 2015 22:04:29 +0000 1       {kubelet 10.9.159.77}   spec.containers{skydns}                 started         Started with docker id aa1eb623bfe984151337f61f3227add92e2703da8f51e98dc47dbb84255be29b
  Thu, 18 Jun 2015 22:04:29 +0000       Thu, 18 Jun 2015 22:04:29 +0000 1       {kubelet 10.9.159.77}   spec.containers{skydns}                 created         Created with docker id aa1eb623bfe984151337f61f3227add92e2703da8f51e98dc47dbb84255be29b
  Thu, 18 Jun 2015 22:01:37 +0000       Thu, 18 Jun 2015 22:04:57 +0000 7       {kubelet 10.9.159.77}   spec.containers{skydns}                 unhealthy       Liveness probe failed: nslookup: can't resolve 'kubernetes.default.kubedomain.local'

  Thu, 18 Jun 2015 22:04:57 +0000       Thu, 18 Jun 2015 22:04:57 +0000 1       {kubelet 10.9.159.77}   spec.containers{skydns} killing Killing aa1eb623bfe984151337f61f3227add92e2703da8f51e98dc47dbb84255be29b
  Thu, 18 Jun 2015 22:04:58 +0000       Thu, 18 Jun 2015 22:04:58 +0000 1       {kubelet 10.9.159.77}   spec.containers{skydns} created Created with docker id de51fe1fdda054f5c261b6292a5cd0bfb5c530f72df043c91e300497bac1d8cf
  Thu, 18 Jun 2015 22:04:58 +0000       Thu, 18 Jun 2015 22:04:58 +0000 1       {kubelet 10.9.159.77}   spec.containers{skydns} started Started with docker id de51fe1fdda054f5c261b6292a5cd0bfb5c530f72df043c91e300497bac1d8cf

wwserver60 ~ # 
```

It looks like it's getting killed and re-created continuously :(

**Comment by akamalov** [comment]
Removed liveness probe to see if it is causing a problem:

```
livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - nslookup kubernetes.default.kubedomain.local localhost >/dev/null
``` 

And it looks like ```skydns``` is staying up. However looking further into ```kube-dns```, I can see that it is not even listening on port ```:53```:

```
/ # uname -a
Linux kube-dns-v3-judq6 4.0.3 #2 SMP Thu May 28 00:30:15 UTC 2015 x86_64 GNU/Linux
/ # netstat -an
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      0 127.0.0.1:7001          0.0.0.0:*               LISTEN      
tcp        0      0 127.0.0.1:4001          0.0.0.0:*               LISTEN      
tcp        0      0 127.0.0.1:2379          0.0.0.0:*               LISTEN      
tcp        0      0 127.0.0.1:2380          0.0.0.0:*               LISTEN      
tcp        0      0 11.14.192.24:40513      10.9.158.219:8888       ESTABLISHED 
tcp        0      0 11.14.192.24:40514      10.9.158.219:8888       ESTABLISHED 
tcp        0      0 127.0.0.1:53123         127.0.0.1:2379          ESTABLISHED 
tcp        0      0 127.0.0.1:4001          127.0.0.1:37917         ESTABLISHED 
tcp        0      0 127.0.0.1:4001          127.0.0.1:37918         ESTABLISHED 
tcp        0      0 127.0.0.1:37918         127.0.0.1:4001          ESTABLISHED 
tcp        0      0 127.0.0.1:37917         127.0.0.1:4001          ESTABLISHED 
tcp        0      0 127.0.0.1:2379          127.0.0.1:53123         ESTABLISHED 
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node Path
/ # 

```
Need to understand better, why would ```sky-dns``` wouldn't listen on port...
