### ISSUE TITLE
Salt requires module.reload to be sprinkled everywhere for systemd

### ISSUE THREAD

**Issue by justinsb** [GoogleCloudPlatform/kubernetes#9860]
Apparently we need:

```
module.wait:
    - name: service.systemctl_reload
    - watch:
      - file: /etc/systemd/system/myservice.service
  ```

for _every_ file that systemd caches.

https://github.com/saltstack/salt/issues/16778#issuecomment-59974857

Currently we're only using systemd on redhat, but I don't see how they managed to sidestep this problem...
