### ISSUE TITLE
ClusterIP in service spec is ignored

### ISSUE THREAD

**Issue by bkeroackdsc** [GoogleCloudPlatform/kubernetes#9981]
Running K8s 0.18.1 on CoreOS alpha on AWS. Using flannel overlay networking.

My kube-apiserver is configured with the following IP range: ``--service-cluster-ip-range=10.100.0.0/16``

I'm using the following service definition for k8s DNS:

```yaml
apiVersion: v1beta3
kind: Service
metadata:
  name: kube-dns
  namespace: default
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeDNS"
spec:
  selector:
    k8s-app: kube-dns
  clusterIP: 10.100.83.255
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
```

Despite specifying ``clusterIP`` and providing an IP that is within the legal range, every time I create this service it is brought up with a different random IP:

```
NAME               LABELS                                                                           SELECTOR                     IP(S)            PORT(S)
kube-dns           k8s-app=kube-dns,kubernetes.io/cluster-service=true,kubernetes.io/name=KubeDNS   k8s-app=kube-dns             10.100.199.245   53/UDP
                                                                                                                                                  53/TCP
```

Any ideas why?
